// GENERATED CODE - DO NOT MODIFY BY HAND
// Source: variables.tokens.json
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class TokensLight {
  static const Color textPrimary900 = Color(0xff181d27);
  static const Color textTertiary600 = Color(0xff535862);
  static const Color textErrorPrimary600 = Color(0xffd92d20);
  static const Color textWarningPrimary600 = Color(0xffca8504);
  static const Color textSuccessPrimary600 = Color(0xff079455);
  static const Color textWhite = Color(0xffffffff);
  static const Color textSecondary700 = Color(0xff414651);
  static const Color textDisabled = Color(0xff717680);
  static const Color textSecondaryHover = Color(0xff252b37);
  static const Color textTertiaryHover = Color(0xff414651);
  static const Color textBrandSecondary700 = Color(0xffe04f16);
  static const Color textPlaceholder = Color(0xff717680);
  static const Color textPlaceholderSubtle = Color(0xffd5d7da);
  static const Color textBrandTertiary600 = Color(0xffb93815);
  static const Color textQuaternary500 = Color(0xff717680);
  static const Color textBrandPrimary900 = Color(0xfffc7701);
  static const Color textPrimaryOnBrand = Color(0xffffffff);
  static const Color textSecondaryOnBrand = Color(0xfff9dbaf);
  static const Color textTertiaryOnBrand = Color(0xfff9dbaf);
  static const Color textQuaternaryOnBrand = Color(0xfff7b27a);
  static const Color textBrandTertiaryAlt = Color(0xffb93815);
  static const Color borderSecondary = Color(0xffe9eaeb);
  static const Color borderErrorSubtle = Color(0xfffda29b);
  static const Color borderPrimary = Color(0xffd5d7da);
  static const Color borderBrand = Color(0xfffc7701);
  static const Color borderDisabled = Color(0xffd5d7da);
  static const Color borderError = Color(0xfff04438);
  static const Color borderDisabledSubtle = Color(0xffe9eaeb);
  static const Color borderTertiary = Color(0xfff5f5f5);
  static const Color borderBrandAlt = Color(0xffe04f16);
  static const Color bgPrimary = Color(0xffffffff);
  static const Color bgTertiary = Color(0xfff5f5f5);
  static const Color bgBrandPrimary = Color(0xfffef6ee);
  static const Color bgErrorSecondary = Color(0xfffee4e2);
  static const Color bgWarningPrimary = Color(0xfffefbe8);
  static const Color bgWarningSecondary = Color(0xfffef7c3);
  static const Color bgSuccessPrimary = Color(0xffecfdf3);
  static const Color bgSuccessSecondary = Color(0xffdcfae6);
  static const Color bgBrandSolid = Color(0xfffc7701);
  static const Color bgSecondarySolid = Color(0xff535862);
  static const Color bgErrorSolid = Color(0xffd92d20);
  static const Color bgWarningSolid = Color(0xffeaaa08);
  static const Color bgSuccessSolid = Color(0xff079455);
  static const Color bgSecondaryHover = Color(0xfff5f5f5);
  static const Color bgPrimaryHover = Color(0xfffafafa);
  static const Color bgDisabled = Color(0xfff5f5f5);
  static const Color bgActive = Color(0xfffafafa);
  static const Color bgBrandSolidHover = Color(0xffe04f16);
  static const Color bgErrorPrimary = Color(0xfffef3f2);
  static const Color bgBrandSecondary = Color(0xfffdead7);
  static const Color bgSecondary = Color(0xfffafafa);
  static const Color bgDisabledSubtle = Color(0xfffafafa);
  static const Color bgQuaternary = Color(0xffe9eaeb);
  static const Color bgPrimaryAlt = Color(0xffffffff);
  static const Color bgBrandPrimaryAlt = Color(0xfffef6ee);
  static const Color bgSecondaryAlt = Color(0xfffafafa);
  static const Color bgOverlay = Color(0xff0a0d12);
  static const Color bgSecondarySubtle = Color(0xfffdfdfd);
  static const Color bgBrandSection = Color(0xffb93815);
  static const Color bgBrandSectionSubtle = Color(0xffe04f16);
  static const Color bgPrimarySolid = Color(0xff0a0d12);
  static const Color bgMobileSign = Color(0xffffffff);
  static const Color bgMobilePrimary = Color(0xfff5f5f5);
  static const Color fgSecondary700 = Color(0xff414651);
  static const Color fgWarningPrimary = Color(0xffeaaa08);
  static const Color fgSuccessPrimary = Color(0xff079455);
  static const Color fgWhite = Color(0xffffffff);
  static const Color fgSuccessSecondary = Color(0xff17b26a);
  static const Color fgSecondaryHover = Color(0xff252b37);
  static const Color fgPrimary900 = Color(0xff181d27);
  static const Color fgDisabled = Color(0xffa4a7ae);
  static const Color fgQuaternary500 = Color(0xff717680);
  static const Color fgQuaternaryHover = Color(0xff535862);
  static const Color fgBrandSecondary500 = Color(0xfffc7701);
  static const Color fgBrandPrimary = Color(0xfffc7701);
  static const Color fgQuinary400 = Color(0xffa4a7ae);
  static const Color fgQuinaryHover = Color(0xff717680);
  static const Color fgErrorPrimary = Color(0xffd92d20);
  static const Color fgDisabledSubtle = Color(0xffd5d7da);
  static const Color fgWarningSecondary = Color(0xfffac515);
  static const Color fgErrorSecondary = Color(0xfff04438);
  static const Color fgSenary300 = Color(0xffd5d7da);
  static const Color fgTertiary600 = Color(0xff535862);
  static const Color fgTertiaryHover = Color(0xff414651);
  static const Color fgBrandPrimaryAlt = Color(0xfffc7701);
  static const Color shadowXs = Color(0x0d0a0d12);
  static const Color shadowSm02 = Color(0x1a0a0d12);
  static const Color shadowLg01 = Color(0x140a0d12);
  static const Color shadowLg02 = Color(0x080a0d12);
  static const Color shadowSm01 = Color(0x1a0a0d12);
  static const Color shadow3xl01 = Color(0x240a0d12);
  static const Color shadow2xl01 = Color(0x2e0a0d12);
  static const Color shadowMd01 = Color(0x1a0a0d12);
  static const Color shadowMd02 = Color(0x0f0a0d12);
  static const Color shadowXl01 = Color(0x140a0d12);
  static const Color shadowXl02 = Color(0x080a0d12);
  static const Color shadowSkeumorphicInner = Color(0x0d0a0d12);
  static const Color shadowSkeumorphicInnerBorder = Color(0x2e0a0d12);
  static const Color shadowLg03 = Color(0x0a0a0d12);
  static const Color shadowXl03 = Color(0x0a0a0d12);
  static const Color shadow2xl02 = Color(0x0a0a0d12);
  static const Color shadow3xl02 = Color(0x0a0a0d12);
  static const Color shadowMainCentreMd = Color(0x240a0d12);
  static const Color shadowMainCentreLg = Color(0x2e0a0d12);
  static const Color shadowOverlayLg = Color(0x1f0a0d12);
  static const Color shadowGridMd = Color(0x140a0d12);
  static const Color focusRing = Color(0xfffc7701);
  static const Color focusRingError = Color(0xfff04438);
  static const Color utilityBlue600 = Color(0xff1570ef);
  static const Color utilityBlue700 = Color(0xff175cd3);
  static const Color utilityBlue500 = Color(0xff2e90fa);
  static const Color utilityBlue200 = Color(0xffb2ddff);
  static const Color utilityBlue50 = Color(0xffeff8ff);
  static const Color utilityBlue100 = Color(0xffd1e9ff);
  static const Color utilityBlue400 = Color(0xff53b1fd);
  static const Color utilityBlue300 = Color(0xff84caff);
  static const Color utilityBrand600 = Color(0xffe04f16);
  static const Color utilityBrand700 = Color(0xffb93815);
  static const Color utilityBrand500 = Color(0xfffc7701);
  static const Color utilityBrand200 = Color(0xfff9dbaf);
  static const Color utilityBrand50 = Color(0xfffef6ee);
  static const Color utilityBrand100 = Color(0xfffdead7);
  static const Color utilityBrand400 = Color(0xfff38744);
  static const Color utilityBrand50Alt = Color(0xfffef6ee);
  static const Color utilityBrand100Alt = Color(0xfffdead7);
  static const Color utilityBrand200Alt = Color(0xfff9dbaf);
  static const Color utilityBrand400Alt = Color(0xfff38744);
  static const Color utilityBrand500Alt = Color(0xfffc7701);
  static const Color utilityBrand600Alt = Color(0xffe04f16);
  static const Color utilityBrand700Alt = Color(0xffb93815);
  static const Color utilityBrand300 = Color(0xfff7b27a);
  static const Color utilityBrand900 = Color(0xff772917);
  static const Color utilityBrand800 = Color(0xff932f19);
  static const Color utilityBrand300Alt = Color(0xfff7b27a);
  static const Color utilityBrand800Alt = Color(0xff932f19);
  static const Color utilityBrand900Alt = Color(0xff772917);
  static const Color utilityGray700 = Color(0xff414651);
  static const Color utilityGray600 = Color(0xff535862);
  static const Color utilityGray500 = Color(0xff717680);
  static const Color utilityGray200 = Color(0xffe9eaeb);
  static const Color utilityGray50 = Color(0xfffafafa);
  static const Color utilityGray100 = Color(0xfff5f5f5);
  static const Color utilityGray400 = Color(0xffa4a7ae);
  static const Color utilityGray300 = Color(0xffd5d7da);
  static const Color utilityGray900 = Color(0xff181d27);
  static const Color utilityGray800 = Color(0xff252b37);
  static const Color utilityError600 = Color(0xffd92d20);
  static const Color utilityError700 = Color(0xffb42318);
  static const Color utilityError500 = Color(0xfff04438);
  static const Color utilityError200 = Color(0xfffecdca);
  static const Color utilityError50 = Color(0xfffef3f2);
  static const Color utilityError100 = Color(0xfffee4e2);
  static const Color utilityError400 = Color(0xfff97066);
  static const Color utilityError300 = Color(0xfffda29b);
  static const Color utilityWarning600 = Color(0xffca8504);
  static const Color utilityWarning700 = Color(0xffa15c07);
  static const Color utilityWarning500 = Color(0xffeaaa08);
  static const Color utilityWarning200 = Color(0xfffeee95);
  static const Color utilityWarning50 = Color(0xfffefbe8);
  static const Color utilityWarning100 = Color(0xfffef7c3);
  static const Color utilityWarning400 = Color(0xfffac515);
  static const Color utilityWarning300 = Color(0xfffde272);
  static const Color utilitySuccess600 = Color(0xff079455);
  static const Color utilitySuccess700 = Color(0xff067647);
  static const Color utilitySuccess500 = Color(0xff17b26a);
  static const Color utilitySuccess200 = Color(0xffabefc6);
  static const Color utilitySuccess50 = Color(0xffecfdf3);
  static const Color utilitySuccess100 = Color(0xffdcfae6);
  static const Color utilitySuccess400 = Color(0xff47cd89);
  static const Color utilitySuccess300 = Color(0xff75e0a7);
  static const Color utilityOrange600 = Color(0xffe04f16);
  static const Color utilityOrange700 = Color(0xffb93815);
  static const Color utilityOrange500 = Color(0xffef6820);
  static const Color utilityOrange200 = Color(0xfff9dbaf);
  static const Color utilityOrange50 = Color(0xfffef6ee);
  static const Color utilityOrange100 = Color(0xfffdead7);
  static const Color utilityOrange400 = Color(0xfff38744);
  static const Color utilityOrange300 = Color(0xfff7b27a);
  static const Color utilityBlueDark600 = Color(0xff155eef);
  static const Color utilityBlueDark700 = Color(0xff004eeb);
  static const Color utilityBlueDark500 = Color(0xff2970ff);
  static const Color utilityBlueDark200 = Color(0xffb2ccff);
  static const Color utilityBlueDark50 = Color(0xffeff4ff);
  static const Color utilityBlueDark100 = Color(0xffd1e0ff);
  static const Color utilityBlueDark400 = Color(0xff528bff);
  static const Color utilityBlueDark300 = Color(0xff84adff);
  static const Color utilityIndigo600 = Color(0xff444ce7);
  static const Color utilityIndigo700 = Color(0xff3538cd);
  static const Color utilityIndigo500 = Color(0xff6172f3);
  static const Color utilityIndigo200 = Color(0xffc7d7fe);
  static const Color utilityIndigo50 = Color(0xffeef4ff);
  static const Color utilityIndigo100 = Color(0xffe0eaff);
  static const Color utilityIndigo400 = Color(0xff8098f9);
  static const Color utilityIndigo300 = Color(0xffa4bcfd);
  static const Color utilityFuchsia600 = Color(0xffba24d5);
  static const Color utilityFuchsia700 = Color(0xff9f1ab1);
  static const Color utilityFuchsia500 = Color(0xffd444f1);
  static const Color utilityFuchsia200 = Color(0xfff6d0fe);
  static const Color utilityFuchsia50 = Color(0xfffdf4ff);
  static const Color utilityFuchsia100 = Color(0xfffbe8ff);
  static const Color utilityFuchsia400 = Color(0xffe478fa);
  static const Color utilityFuchsia300 = Color(0xffeeaafd);
  static const Color utilityPink600 = Color(0xffdd2590);
  static const Color utilityPink700 = Color(0xffc11574);
  static const Color utilityPink500 = Color(0xffee46bc);
  static const Color utilityPink200 = Color(0xfffcceee);
  static const Color utilityPink50 = Color(0xfffdf2fa);
  static const Color utilityPink100 = Color(0xfffce7f6);
  static const Color utilityPink400 = Color(0xfff670c7);
  static const Color utilityPink300 = Color(0xfffaa7e0);
  static const Color utilityPurple600 = Color(0xff6938ef);
  static const Color utilityPurple700 = Color(0xff5925dc);
  static const Color utilityPurple500 = Color(0xff7a5af8);
  static const Color utilityPurple200 = Color(0xffd9d6fe);
  static const Color utilityPurple50 = Color(0xfff4f3ff);
  static const Color utilityPurple100 = Color(0xffebe9fe);
  static const Color utilityPurple400 = Color(0xff9b8afb);
  static const Color utilityPurple300 = Color(0xffbdb4fe);
  static const Color utilityOrangeDark600 = Color(0xffe62e05);
  static const Color utilityOrangeDark700 = Color(0xffbc1b06);
  static const Color utilityOrangeDark500 = Color(0xffff4405);
  static const Color utilityOrangeDark200 = Color(0xffffd6ae);
  static const Color utilityOrangeDark50 = Color(0xfffff4ed);
  static const Color utilityOrangeDark100 = Color(0xffffe6d5);
  static const Color utilityOrangeDark400 = Color(0xffff692e);
  static const Color utilityOrangeDark300 = Color(0xffff9c66);
  static const Color utilityBlueLight600 = Color(0xff0086c9);
  static const Color utilityBlueLight700 = Color(0xff026aa2);
  static const Color utilityBlueLight500 = Color(0xff0ba5ec);
  static const Color utilityBlueLight200 = Color(0xffb9e6fe);
  static const Color utilityBlueLight50 = Color(0xfff0f9ff);
  static const Color utilityBlueLight100 = Color(0xffe0f2fe);
  static const Color utilityBlueLight400 = Color(0xff36bffa);
  static const Color utilityBlueLight300 = Color(0xff7cd4fd);
  static const Color utilityGrayBlue600 = Color(0xff3e4784);
  static const Color utilityGrayBlue700 = Color(0xff363f72);
  static const Color utilityGrayBlue500 = Color(0xff4e5ba6);
  static const Color utilityGrayBlue200 = Color(0xffd5d9eb);
  static const Color utilityGrayBlue50 = Color(0xfff8f9fc);
  static const Color utilityGrayBlue100 = Color(0xffeaecf5);
  static const Color utilityGrayBlue400 = Color(0xff717bbc);
  static const Color utilityGrayBlue300 = Color(0xffb3b8db);
  static const Color utilityGreen50 = Color(0xffedfcf2);
  static const Color utilityGreen100 = Color(0xffd3f8df);
  static const Color utilityGreen200 = Color(0xffaaf0c4);
  static const Color utilityGreen300 = Color(0xff73e2a3);
  static const Color utilityGreen400 = Color(0xff3ccb7f);
  static const Color utilityGreen500 = Color(0xff16b364);
  static const Color utilityGreen600 = Color(0xff099250);
  static const Color utilityGreen700 = Color(0xff087443);
  static const Color utilityYellow50 = Color(0xfffefbe8);
  static const Color utilityYellow100 = Color(0xfffef7c3);
  static const Color utilityYellow200 = Color(0xfffeee95);
  static const Color utilityYellow300 = Color(0xfffde272);
  static const Color utilityYellow400 = Color(0xfffac515);
  static const Color utilityYellow500 = Color(0xffeaaa08);
  static const Color utilityYellow600 = Color(0xffca8504);
  static const Color utilityYellow700 = Color(0xffa15c07);
  static const Color tooltipSupportingText = Color(0xffd5d7da);
  static const Color buttonPrimaryBg = Color(0xfffc7701);
  static const Color buttonPrimaryBgHover = Color(0xffe04f16);
  static const Color buttonPrimaryFg = Color(0xff000000);
  static const Color buttonPrimaryFgHover = Color(0xff000000);
  static const Color buttonSecondaryBg = Color(0xffffffff);
  static const Color buttonSecondaryBgHover = Color(0xfffafafa);
  static const Color buttonSecondaryFg = Color(0xff414651);
  static const Color buttonSecondaryFgHover = Color(0xff252b37);
  static const Color buttonSecondaryBorder = Color(0xffd5d7da);
  static const Color buttonSecondaryBorderHover = Color(0xffd5d7da);
  static const Color buttonSecondaryColorBg = Color(0xffffffff);
  static const Color buttonSecondaryColorBgHover = Color(0xfffef6ee);
  static const Color buttonSecondaryColorBorderHover = Color(0xfff7b27a);
  static const Color buttonSecondaryColorBorder = Color(0xfff7b27a);
  static const Color buttonSecondaryColorFg = Color(0xffe04f16);
  static const Color buttonSecondaryColorFgHover = Color(0xffb93815);
  static const Color buttonPrimaryErrorFg = Color(0xffffffff);
  static const Color buttonPrimaryErrorFgHover = Color(0xffffffff);
  static const Color buttonPrimaryErrorBg = Color(0xffd92d20);
  static const Color buttonPrimaryErrorBgHover = Color(0xffb42318);
  static const Color buttonSecondaryErrorFg = Color(0xffb42318);
  static const Color buttonSecondaryErrorFgHover = Color(0xff912018);
  static const Color buttonSecondaryErrorBg = Color(0xffffffff);
  static const Color buttonSecondaryErrorBgHover = Color(0xfffef3f2);
  static const Color buttonSecondaryErrorBorder = Color(0xfffda29b);
  static const Color buttonSecondaryErrorBorderHover = Color(0xfffda29b);
  static const Color buttonTertiaryFg = Color(0xff535862);
  static const Color buttonTertiaryFgHover = Color(0xff414651);
  static const Color buttonTertiaryBgHover = Color(0xfffafafa);
  static const Color buttonTertiaryColorFg = Color(0xfffc7701);
  static const Color buttonTertiaryColorFgHover = Color(0xffe04f16);
  static const Color buttonTertiaryColorBgHover = Color(0xfffef6ee);
  static const Color buttonTertiaryErrorFg = Color(0xffb42318);
  static const Color buttonTertiaryErrorFgHover = Color(0xff912018);
  static const Color buttonTertiaryErrorBgHover = Color(0xfffef3f2);
  static const Color buttonOutlineFg = Color(0xff0a0d12);
  static const Color buttonOutlineFgHover = Color(0xff252b37);
  static const Color buttonOutlineBg = Color(0xffffffff);
  static const Color buttonOutlineBgHover = Color(0xfffafafa);
  static const Color buttonOutlineBorder = Color(0xff181d27);
  static const Color buttonOutlineBorderHover = Color(0xff0a0d12);
  static const Color wysiwygEditorIconFg = Color(0xffa4a7ae);
  static const Color wysiwygEditorIconFgActive = Color(0xff717680);
  static const Color avatarContrastBorder = Color(0x14000000);
  static const Color avatarProfilePhotoBorder = Color(0xffffffff);
  static const Color avatarBg = Color(0xfff5f5f5);
  static const Color avatarStylesBgNeutral = Color(0xffe0e0e0);
  static const Color breadcrumbFg = Color(0xff535862);
  static const Color breadcrumbFgHover = Color(0xff414651);
  static const Color breadcrumbBgHover = Color(0xfffafafa);
  static const Color breadcrumbBrandBgHover = Color(0xfffef6ee);
  static const Color breadcrumbBrandFgHover = Color(0xffb93815);
  static const Color breadcrumbIconFg = Color(0xff717680);
  static const Color breadcrumbIconFgHover = Color(0xff414651);
  static const Color breadcrumbBrandIconFgHover = Color(0xffb93815);
  static const Color featuredIconModernBorder = Color(0xffe9eaeb);
  static const Color featuredIconLightFgBrand = Color(0xfffc7701);
  static const Color featuredIconLightFgGray = Color(0xff717680);
  static const Color featuredIconLightFgError = Color(0xfff04438);
  static const Color featuredIconLightFgWarning = Color(0xffeaaa08);
  static const Color featuredIconLightFgSuccess = Color(0xff17b26a);
  static const Color featuredIconDarkFgBrand = Color(0xffffffff);
  static const Color featuredIconDarkFgGray = Color(0xffffffff);
  static const Color featuredIconDarkFgError = Color(0xffffffff);
  static const Color featuredIconDarkFgWarning = Color(0xffffffff);
  static const Color featuredIconDarkFgSuccess = Color(0xffffffff);
  static const Color iconFgBrand = Color(0xfffc7701);
  static const Color iconFgBrandOnBrand = Color(0xfff9dbaf);
  static const Color socialIconFgX = Color(0xff242e36);
  static const Color socialIconFgApple = Color(0xff000000);
  static const Color socialIconFgGithub = Color(0xff000000);
  static const Color socialIconFgAngellist = Color(0xff000000);
  static const Color socialIconFgTumblr = Color(0xff001935);
  static const Color socialIconFgInstagram = Color(0xff000100);
  static const Color navItemIconFg = Color(0xff717680);
  static const Color navItemIconFgActive = Color(0xff717680);
  static const Color navItemButtonIconFg = Color(0xff717680);
  static const Color navItemButtonIconFgActive = Color(0xff414651);
  static const Color sliderHandleBorder = Color(0xfffc7701);
  static const Color sliderHandleBg = Color(0xffffffff);
  static const Color headerAbstract50Bg = Color(0xfffef6ee);
  static const Color headerAbstract100Bg = Color(0xfffdead7);
  static const Color headerAbstract200Bg = Color(0xfff9dbaf);
  static const Color headerAbstract300Bg = Color(0xfff7b27a);
  static const Color screenMockupBorder = Color(0xff181d27);
  static const Color footerButtonFg = Color(0xfff9dbaf);
  static const Color footerButtonFgHover = Color(0xffffffff);
  static const Color footerBadgeFg = Color(0xff067647);
  static const Color footerBadgeBorder = Color(0xffabefc6);
  static const Color footerBadgeBg = Color(0xffecfdf3);
  static const Color appStoreBadgeBorder = Color(0xffa6a6a6);
  static const Color thumbnailBadgeBrandFg = Color(0xffb93815);
  static const Color thumbnailBadgeSuccessFg = Color(0xff067647);
  static const Color toggleButtonFgDisabled = Color(0xfffafafa);
  static const Color toggleBorder = Color(0xffd5d7da);
  static const Color toggleSlimBorderPressed = Color(0xfffc7701);
  static const Color toggleSlimBorderPressedHover = Color(0xffe04f16);
  static const Color alphaWhite90 = Color(0xe6ffffff);
  static const Color alphaWhite80 = Color(0xccffffff);
  static const Color alphaWhite70 = Color(0xb3ffffff);
  static const Color alphaWhite60 = Color(0x99ffffff);
  static const Color alphaWhite50 = Color(0x80ffffff);
  static const Color alphaWhite40 = Color(0x66ffffff);
  static const Color alphaWhite30 = Color(0x4dffffff);
  static const Color alphaWhite20 = Color(0x33ffffff);
  static const Color alphaWhite10 = Color(0x1affffff);
  static const Color alphaBlack10 = Color(0x1a000000);
  static const Color alphaBlack20 = Color(0x33000000);
  static const Color alphaBlack30 = Color(0x4d000000);
  static const Color alphaBlack40 = Color(0x66000000);
  static const Color alphaBlack50 = Color(0x80000000);
  static const Color alphaBlack60 = Color(0x99000000);
  static const Color alphaBlack70 = Color(0xb3000000);
  static const Color alphaBlack80 = Color(0xcc000000);
  static const Color alphaBlack90 = Color(0xe6000000);
  static const Color alphaBlack100 = Color(0xff000000);
  static const Color alphaWhite100 = Color(0xffffffff);
  static const Color alphaWhite5 = Color(0x0dffffff);
  static const Color alphaWhite2 = Color(0x05ffffff);
  static const Color alphaBlack5 = Color(0x0d000000);
  static const Color alphaBlack2 = Color(0x05000000);
}

class TokensDark {
  static const Color textPrimary900 = Color(0xfff7f7f7);
  static const Color textTertiary600 = Color(0xff94979c);
  static const Color textErrorPrimary600 = Color(0xfff97066);
  static const Color textWarningPrimary600 = Color(0xfffac515);
  static const Color textSuccessPrimary600 = Color(0xff47cd89);
  static const Color textWhite = Color(0xffffffff);
  static const Color textSecondary700 = Color(0xffcecfd2);
  static const Color textDisabled = Color(0xff85888e);
  static const Color textSecondaryHover = Color(0xffececed);
  static const Color textTertiaryHover = Color(0xffcecfd2);
  static const Color textBrandSecondary700 = Color(0xfff38744);
  static const Color textPlaceholder = Color(0xff85888e);
  static const Color textPlaceholderSubtle = Color(0xff373a41);
  static const Color textBrandTertiary600 = Color(0xfffc7701);
  static const Color textQuaternary500 = Color(0xff94979c);
  static const Color textBrandPrimary900 = Color(0xfffc7701);
  static const Color textPrimaryOnBrand = Color(0xffffffff);
  static const Color textSecondaryOnBrand = Color(0xffcecfd2);
  static const Color textTertiaryOnBrand = Color(0xff94979c);
  static const Color textQuaternaryOnBrand = Color(0xff94979c);
  static const Color textBrandTertiaryAlt = Color(0xffe04f16);
  static const Color borderSecondary = Color(0xff22262f);
  static const Color borderErrorSubtle = Color(0xfff97066);
  static const Color borderPrimary = Color(0xff373a41);
  static const Color borderBrand = Color(0xfff38744);
  static const Color borderDisabled = Color(0xff373a41);
  static const Color borderError = Color(0xfff97066);
  static const Color borderDisabledSubtle = Color(0xff22262f);
  static const Color borderTertiary = Color(0xff13161b);
  static const Color borderBrandAlt = Color(0xff373a41);
  static const Color bgPrimary = Color(0xff22262f);
  static const Color bgTertiary = Color(0xff0c0e12);
  static const Color bgBrandPrimary = Color(0xff511c10);
  static const Color bgErrorSecondary = Color(0xffd92d20);
  static const Color bgWarningPrimary = Color(0xffeaaa08);
  static const Color bgWarningSecondary = Color(0xffeaaa08);
  static const Color bgSuccessPrimary = Color(0xff17b26a);
  static const Color bgSuccessSecondary = Color(0xff079455);
  static const Color bgBrandSolid = Color(0xfffc7701);
  static const Color bgSecondarySolid = Color(0xff61656c);
  static const Color bgErrorSolid = Color(0xffd92d20);
  static const Color bgWarningSolid = Color(0xffeaaa08);
  static const Color bgSuccessSolid = Color(0xff079455);
  static const Color bgSecondaryHover = Color(0xff22262f);
  static const Color bgPrimaryHover = Color(0xff22262f);
  static const Color bgDisabled = Color(0xff22262f);
  static const Color bgActive = Color(0xff22262f);
  static const Color bgBrandSolidHover = Color(0xffe04f16);
  static const Color bgErrorPrimary = Color(0xfff04438);
  static const Color bgBrandSecondary = Color(0xfffc7701);
  static const Color bgSecondary = Color(0xff13161b);
  static const Color bgDisabledSubtle = Color(0xff13161b);
  static const Color bgQuaternary = Color(0xff0a0d12);
  static const Color bgPrimaryAlt = Color(0xff181d27);
  static const Color bgBrandPrimaryAlt = Color(0xff13161b);
  static const Color bgSecondaryAlt = Color(0xff22262f);
  static const Color bgOverlay = Color(0xff22262f);
  static const Color bgSecondarySubtle = Color(0xff13161b);
  static const Color bgBrandSection = Color(0xff13161b);
  static const Color bgBrandSectionSubtle = Color(0xff22262f);
  static const Color bgPrimarySolid = Color(0xff13161b);
  static const Color bgMobileSign = Color(0xff13161b);
  static const Color bgMobilePrimary = Color(0xff13161b);
  static const Color fgSecondary700 = Color(0xffcecfd2);
  static const Color fgWarningPrimary = Color(0xffeaaa08);
  static const Color fgSuccessPrimary = Color(0xff17b26a);
  static const Color fgWhite = Color(0xffffffff);
  static const Color fgSuccessSecondary = Color(0xff47cd89);
  static const Color fgSecondaryHover = Color(0xffececed);
  static const Color fgPrimary900 = Color(0xffffffff);
  static const Color fgDisabled = Color(0xff85888e);
  static const Color fgQuaternary500 = Color(0xff94979c);
  static const Color fgQuaternaryHover = Color(0xffcecfd2);
  static const Color fgBrandSecondary500 = Color(0xfffc7701);
  static const Color fgBrandPrimary = Color(0xfffc7701);
  static const Color fgQuinary400 = Color(0xff85888e);
  static const Color fgQuinaryHover = Color(0xff94979c);
  static const Color fgErrorPrimary = Color(0xfff04438);
  static const Color fgDisabledSubtle = Color(0xff61656c);
  static const Color fgWarningSecondary = Color(0xfffac515);
  static const Color fgErrorSecondary = Color(0xfff97066);
  static const Color fgSenary300 = Color(0xff61656c);
  static const Color fgTertiary600 = Color(0xff94979c);
  static const Color fgTertiaryHover = Color(0xffcecfd2);
  static const Color fgBrandPrimaryAlt = Color(0xffcecfd2);
  static const Color shadowXs = Color(0x00ffffff);
  static const Color shadowSm02 = Color(0x00ffffff);
  static const Color shadowLg01 = Color(0x00ffffff);
  static const Color shadowLg02 = Color(0x00ffffff);
  static const Color shadowSm01 = Color(0x00ffffff);
  static const Color shadow3xl01 = Color(0x00ffffff);
  static const Color shadow2xl01 = Color(0x00ffffff);
  static const Color shadowMd01 = Color(0x00ffffff);
  static const Color shadowMd02 = Color(0x00ffffff);
  static const Color shadowXl01 = Color(0x00ffffff);
  static const Color shadowXl02 = Color(0x00ffffff);
  static const Color shadowSkeumorphicInner = Color(0x0d0c0e12);
  static const Color shadowSkeumorphicInnerBorder = Color(0x2e0c0e12);
  static const Color shadowLg03 = Color(0x00ffffff);
  static const Color shadowXl03 = Color(0x00ffffff);
  static const Color shadow2xl02 = Color(0x00ffffff);
  static const Color shadow3xl02 = Color(0x00ffffff);
  static const Color shadowMainCentreMd = Color(0x00ffffff);
  static const Color shadowMainCentreLg = Color(0x00ffffff);
  static const Color shadowOverlayLg = Color(0x00ffffff);
  static const Color shadowGridMd = Color(0x00ffffff);
  static const Color focusRing = Color(0xfffc7701);
  static const Color focusRingError = Color(0xfff04438);
  static const Color utilityBlue600 = Color(0xff53b1fd);
  static const Color utilityBlue700 = Color(0xff84caff);
  static const Color utilityBlue500 = Color(0xff2e90fa);
  static const Color utilityBlue200 = Color(0xff1849a9);
  static const Color utilityBlue50 = Color(0xff102a56);
  static const Color utilityBlue100 = Color(0xff194185);
  static const Color utilityBlue400 = Color(0xff1570ef);
  static const Color utilityBlue300 = Color(0xff175cd3);
  static const Color utilityBrand600 = Color(0xfff38744);
  static const Color utilityBrand700 = Color(0xfff7b27a);
  static const Color utilityBrand500 = Color(0xfffc7701);
  static const Color utilityBrand200 = Color(0xff932f19);
  static const Color utilityBrand50 = Color(0xff511c10);
  static const Color utilityBrand100 = Color(0xff772917);
  static const Color utilityBrand400 = Color(0xffe04f16);
  static const Color utilityBrand50Alt = Color(0xff13161b);
  static const Color utilityBrand100Alt = Color(0xff22262f);
  static const Color utilityBrand200Alt = Color(0xff373a41);
  static const Color utilityBrand400Alt = Color(0xff61656c);
  static const Color utilityBrand500Alt = Color(0xff85888e);
  static const Color utilityBrand600Alt = Color(0xff94979c);
  static const Color utilityBrand700Alt = Color(0xffcecfd2);
  static const Color utilityBrand300 = Color(0xffb93815);
  static const Color utilityBrand900 = Color(0xfffdead7);
  static const Color utilityBrand800 = Color(0xfff9dbaf);
  static const Color utilityBrand300Alt = Color(0xff373a41);
  static const Color utilityBrand800Alt = Color(0xffececed);
  static const Color utilityBrand900Alt = Color(0xfff0f0f1);
  static const Color utilityGray700 = Color(0xffcecfd2);
  static const Color utilityGray600 = Color(0xff94979c);
  static const Color utilityGray500 = Color(0xff85888e);
  static const Color utilityGray200 = Color(0xff373a41);
  static const Color utilityGray50 = Color(0xff13161b);
  static const Color utilityGray100 = Color(0xff22262f);
  static const Color utilityGray400 = Color(0xff61656c);
  static const Color utilityGray300 = Color(0xff373a41);
  static const Color utilityGray900 = Color(0xfff0f0f1);
  static const Color utilityGray800 = Color(0xffececed);
  static const Color utilityError600 = Color(0xfff97066);
  static const Color utilityError700 = Color(0xfffda29b);
  static const Color utilityError500 = Color(0xfff04438);
  static const Color utilityError200 = Color(0xff912018);
  static const Color utilityError50 = Color(0xff55160c);
  static const Color utilityError100 = Color(0xff7a271a);
  static const Color utilityError400 = Color(0xffd92d20);
  static const Color utilityError300 = Color(0xffb42318);
  static const Color utilityWarning600 = Color(0xfffac515);
  static const Color utilityWarning700 = Color(0xfffde272);
  static const Color utilityWarning500 = Color(0xffeaaa08);
  static const Color utilityWarning200 = Color(0xff854a0e);
  static const Color utilityWarning50 = Color(0xff542c0d);
  static const Color utilityWarning100 = Color(0xff713b12);
  static const Color utilityWarning400 = Color(0xffca8504);
  static const Color utilityWarning300 = Color(0xffa15c07);
  static const Color utilitySuccess600 = Color(0xff47cd89);
  static const Color utilitySuccess700 = Color(0xff75e0a7);
  static const Color utilitySuccess500 = Color(0xff17b26a);
  static const Color utilitySuccess200 = Color(0xff085d3a);
  static const Color utilitySuccess50 = Color(0xff053321);
  static const Color utilitySuccess100 = Color(0xff074d31);
  static const Color utilitySuccess400 = Color(0xff079455);
  static const Color utilitySuccess300 = Color(0xff067647);
  static const Color utilityOrange600 = Color(0xfff38744);
  static const Color utilityOrange700 = Color(0xfff7b27a);
  static const Color utilityOrange500 = Color(0xffef6820);
  static const Color utilityOrange200 = Color(0xff932f19);
  static const Color utilityOrange50 = Color(0xff511c10);
  static const Color utilityOrange100 = Color(0xff772917);
  static const Color utilityOrange400 = Color(0xffe04f16);
  static const Color utilityOrange300 = Color(0xffb93815);
  static const Color utilityBlueDark600 = Color(0xff528bff);
  static const Color utilityBlueDark700 = Color(0xff84adff);
  static const Color utilityBlueDark500 = Color(0xff2970ff);
  static const Color utilityBlueDark200 = Color(0xff0040c1);
  static const Color utilityBlueDark50 = Color(0xff002266);
  static const Color utilityBlueDark100 = Color(0xff00359e);
  static const Color utilityBlueDark400 = Color(0xff155eef);
  static const Color utilityBlueDark300 = Color(0xff004eeb);
  static const Color utilityIndigo600 = Color(0xff8098f9);
  static const Color utilityIndigo700 = Color(0xffa4bcfd);
  static const Color utilityIndigo500 = Color(0xff6172f3);
  static const Color utilityIndigo200 = Color(0xff2d31a6);
  static const Color utilityIndigo50 = Color(0xff1f235b);
  static const Color utilityIndigo100 = Color(0xff2d3282);
  static const Color utilityIndigo400 = Color(0xff444ce7);
  static const Color utilityIndigo300 = Color(0xff3538cd);
  static const Color utilityFuchsia600 = Color(0xffe478fa);
  static const Color utilityFuchsia700 = Color(0xffeeaafd);
  static const Color utilityFuchsia500 = Color(0xffd444f1);
  static const Color utilityFuchsia200 = Color(0xff821890);
  static const Color utilityFuchsia50 = Color(0xff47104c);
  static const Color utilityFuchsia100 = Color(0xff6f1877);
  static const Color utilityFuchsia400 = Color(0xffba24d5);
  static const Color utilityFuchsia300 = Color(0xff9f1ab1);
  static const Color utilityPink600 = Color(0xfff670c7);
  static const Color utilityPink700 = Color(0xfffaa7e0);
  static const Color utilityPink500 = Color(0xffee46bc);
  static const Color utilityPink200 = Color(0xff9e165f);
  static const Color utilityPink50 = Color(0xff4e0d30);
  static const Color utilityPink100 = Color(0xff851651);
  static const Color utilityPink400 = Color(0xffdd2590);
  static const Color utilityPink300 = Color(0xffc11574);
  static const Color utilityPurple600 = Color(0xff9b8afb);
  static const Color utilityPurple700 = Color(0xffbdb4fe);
  static const Color utilityPurple500 = Color(0xff7a5af8);
  static const Color utilityPurple200 = Color(0xff4a1fb8);
  static const Color utilityPurple50 = Color(0xff27115f);
  static const Color utilityPurple100 = Color(0xff3e1c96);
  static const Color utilityPurple400 = Color(0xff6938ef);
  static const Color utilityPurple300 = Color(0xff5925dc);
  static const Color utilityOrangeDark600 = Color(0xffff692e);
  static const Color utilityOrangeDark700 = Color(0xffff9c66);
  static const Color utilityOrangeDark500 = Color(0xffff4405);
  static const Color utilityOrangeDark200 = Color(0xff97180c);
  static const Color utilityOrangeDark50 = Color(0xff57130a);
  static const Color utilityOrangeDark100 = Color(0xff771a0d);
  static const Color utilityOrangeDark400 = Color(0xffe62e05);
  static const Color utilityOrangeDark300 = Color(0xffbc1b06);
  static const Color utilityBlueLight600 = Color(0xff36bffa);
  static const Color utilityBlueLight700 = Color(0xff7cd4fd);
  static const Color utilityBlueLight500 = Color(0xff0ba5ec);
  static const Color utilityBlueLight200 = Color(0xff065986);
  static const Color utilityBlueLight50 = Color(0xff062c41);
  static const Color utilityBlueLight100 = Color(0xff0b4a6f);
  static const Color utilityBlueLight400 = Color(0xff0086c9);
  static const Color utilityBlueLight300 = Color(0xff026aa2);
  static const Color utilityGrayBlue600 = Color(0xff717bbc);
  static const Color utilityGrayBlue700 = Color(0xffb3b8db);
  static const Color utilityGrayBlue500 = Color(0xff4e5ba6);
  static const Color utilityGrayBlue200 = Color(0xff293056);
  static const Color utilityGrayBlue50 = Color(0xff0d0f1c);
  static const Color utilityGrayBlue100 = Color(0xff101323);
  static const Color utilityGrayBlue400 = Color(0xff3e4784);
  static const Color utilityGrayBlue300 = Color(0xff363f72);
  static const Color utilityGreen50 = Color(0xff052e1c);
  static const Color utilityGreen100 = Color(0xff084c2e);
  static const Color utilityGreen200 = Color(0xff095c37);
  static const Color utilityGreen300 = Color(0xff087443);
  static const Color utilityGreen400 = Color(0xff099250);
  static const Color utilityGreen500 = Color(0xff16b364);
  static const Color utilityGreen600 = Color(0xff3ccb7f);
  static const Color utilityGreen700 = Color(0xff73e2a3);
  static const Color utilityYellow50 = Color(0xff542c0d);
  static const Color utilityYellow100 = Color(0xff713b12);
  static const Color utilityYellow200 = Color(0xff854a0e);
  static const Color utilityYellow300 = Color(0xffa15c07);
  static const Color utilityYellow400 = Color(0xffca8504);
  static const Color utilityYellow500 = Color(0xffeaaa08);
  static const Color utilityYellow600 = Color(0xfffac515);
  static const Color utilityYellow700 = Color(0xfffde272);
  static const Color tooltipSupportingText = Color(0xffcecfd2);
  static const Color buttonPrimaryBg = Color(0xfffc7701);
  static const Color buttonPrimaryBgHover = Color(0xffe04f16);
  static const Color buttonPrimaryFg = Color(0xff000000);
  static const Color buttonPrimaryFgHover = Color(0xff000000);
  static const Color buttonSecondaryBg = Color(0xff13161b);
  static const Color buttonSecondaryBgHover = Color(0xff22262f);
  static const Color buttonSecondaryFg = Color(0xffcecfd2);
  static const Color buttonSecondaryFgHover = Color(0xfff0f0f1);
  static const Color buttonSecondaryBorder = Color(0xff373a41);
  static const Color buttonSecondaryBorderHover = Color(0xff373a41);
  static const Color buttonSecondaryColorBg = Color(0xff13161b);
  static const Color buttonSecondaryColorBgHover = Color(0xff22262f);
  static const Color buttonSecondaryColorBorderHover = Color(0xff373a41);
  static const Color buttonSecondaryColorBorder = Color(0xff373a41);
  static const Color buttonSecondaryColorFg = Color(0xffcecfd2);
  static const Color buttonSecondaryColorFgHover = Color(0xfff0f0f1);
  static const Color buttonPrimaryErrorFg = Color(0xffffffff);
  static const Color buttonPrimaryErrorFgHover = Color(0xffffffff);
  static const Color buttonPrimaryErrorBg = Color(0xffd92d20);
  static const Color buttonPrimaryErrorBgHover = Color(0xffb42318);
  static const Color buttonSecondaryErrorFg = Color(0xfffecdca);
  static const Color buttonSecondaryErrorFgHover = Color(0xfffee4e2);
  static const Color buttonSecondaryErrorBg = Color(0xff55160c);
  static const Color buttonSecondaryErrorBgHover = Color(0xff7a271a);
  static const Color buttonSecondaryErrorBorder = Color(0xff912018);
  static const Color buttonSecondaryErrorBorderHover = Color(0xffb42318);
  static const Color buttonTertiaryFg = Color(0xff94979c);
  static const Color buttonTertiaryFgHover = Color(0xffececed);
  static const Color buttonTertiaryBgHover = Color(0xff22262f);
  static const Color buttonTertiaryColorFg = Color(0xffcecfd2);
  static const Color buttonTertiaryColorFgHover = Color(0xfff0f0f1);
  static const Color buttonTertiaryColorBgHover = Color(0xff22262f);
  static const Color buttonTertiaryErrorFg = Color(0xfffda29b);
  static const Color buttonTertiaryErrorFgHover = Color(0xfffecdca);
  static const Color buttonTertiaryErrorBgHover = Color(0xff7a271a);
  static const Color buttonOutlineFg = Color(0xfffafafa);
  static const Color buttonOutlineFgHover = Color(0xfff0f0f1);
  static const Color buttonOutlineBg = Color(0xff13161b);
  static const Color buttonOutlineBgHover = Color(0xff22262f);
  static const Color buttonOutlineBorder = Color(0xff94979c);
  static const Color buttonOutlineBorderHover = Color(0xfff0f0f1);
  static const Color wysiwygEditorIconFg = Color(0xff94979c);
  static const Color wysiwygEditorIconFgActive = Color(0xffffffff);
  static const Color avatarContrastBorder = Color(0x1fffffff);
  static const Color avatarProfilePhotoBorder = Color(0xff0c0e12);
  static const Color avatarBg = Color(0xff22262f);
  static const Color avatarStylesBgNeutral = Color(0xffe0e0e0);
  static const Color breadcrumbFg = Color(0xffcecfd2);
  static const Color breadcrumbFgHover = Color(0xffffffff);
  static const Color breadcrumbBgHover = Color(0xff22262f);
  static const Color breadcrumbBrandBgHover = Color(0xff22262f);
  static const Color breadcrumbBrandFgHover = Color(0xffffffff);
  static const Color breadcrumbIconFg = Color(0xff94979c);
  static const Color breadcrumbIconFgHover = Color(0xffffffff);
  static const Color breadcrumbBrandIconFgHover = Color(0xffffffff);
  static const Color featuredIconModernBorder = Color(0xff373a41);
  static const Color featuredIconLightFgBrand = Color(0xfff9dbaf);
  static const Color featuredIconLightFgGray = Color(0xffececed);
  static const Color featuredIconLightFgError = Color(0xfffecdca);
  static const Color featuredIconLightFgWarning = Color(0xfffeee95);
  static const Color featuredIconLightFgSuccess = Color(0xffabefc6);
  static const Color featuredIconDarkFgBrand = Color(0xfff9dbaf);
  static const Color featuredIconDarkFgGray = Color(0xffececed);
  static const Color featuredIconDarkFgError = Color(0xfffecdca);
  static const Color featuredIconDarkFgWarning = Color(0xfffeee95);
  static const Color featuredIconDarkFgSuccess = Color(0xffabefc6);
  static const Color iconFgBrand = Color(0xff94979c);
  static const Color iconFgBrandOnBrand = Color(0xff94979c);
  static const Color socialIconFgX = Color(0xffffffff);
  static const Color socialIconFgApple = Color(0xffffffff);
  static const Color socialIconFgGithub = Color(0xffffffff);
  static const Color socialIconFgAngellist = Color(0xffffffff);
  static const Color socialIconFgTumblr = Color(0xffffffff);
  static const Color socialIconFgInstagram = Color(0xffffffff);
  static const Color navItemIconFg = Color(0xff94979c);
  static const Color navItemIconFgActive = Color(0xffcecfd2);
  static const Color navItemButtonIconFg = Color(0xff94979c);
  static const Color navItemButtonIconFgActive = Color(0xffcecfd2);
  static const Color sliderHandleBorder = Color(0xff22262f);
  static const Color sliderHandleBg = Color(0xfffc7701);
  static const Color headerAbstract50Bg = Color(0xff13161b);
  static const Color headerAbstract100Bg = Color(0xff22262f);
  static const Color headerAbstract200Bg = Color(0xff373a41);
  static const Color headerAbstract300Bg = Color(0xff61656c);
  static const Color screenMockupBorder = Color(0xff373a41);
  static const Color footerButtonFg = Color(0xffcecfd2);
  static const Color footerButtonFgHover = Color(0xfff0f0f1);
  static const Color footerBadgeFg = Color(0xffffffff);
  static const Color footerBadgeBorder = Color(0x4dffffff);
  static const Color footerBadgeBg = Color(0x1affffff);
  static const Color appStoreBadgeBorder = Color(0xffffffff);
  static const Color thumbnailBadgeBrandFg = Color(0xffcecfd2);
  static const Color thumbnailBadgeSuccessFg = Color(0xffcecfd2);
  static const Color toggleButtonFgDisabled = Color(0xff61656c);
  static const Color toggleBorder = Color(0x00ffffff);
  static const Color toggleSlimBorderPressed = Color(0x00ffffff);
  static const Color toggleSlimBorderPressedHover = Color(0x00ffffff);
  static const Color alphaWhite90 = Color(0xe60c0e12);
  static const Color alphaWhite80 = Color(0xcc0c0e12);
  static const Color alphaWhite70 = Color(0xb30c0e12);
  static const Color alphaWhite60 = Color(0x990c0e12);
  static const Color alphaWhite50 = Color(0x800c0e12);
  static const Color alphaWhite40 = Color(0x660c0e12);
  static const Color alphaWhite30 = Color(0x4d0c0e12);
  static const Color alphaWhite20 = Color(0x330c0e12);
  static const Color alphaWhite10 = Color(0x1a0c0e12);
  static const Color alphaBlack10 = Color(0x1affffff);
  static const Color alphaBlack20 = Color(0x33ffffff);
  static const Color alphaBlack30 = Color(0x4dffffff);
  static const Color alphaBlack40 = Color(0x66ffffff);
  static const Color alphaBlack50 = Color(0x80ffffff);
  static const Color alphaBlack60 = Color(0x99ffffff);
  static const Color alphaBlack70 = Color(0xb3ffffff);
  static const Color alphaBlack80 = Color(0xccffffff);
  static const Color alphaBlack90 = Color(0xe6ffffff);
  static const Color alphaBlack100 = Color(0xffffffff);
  static const Color alphaWhite100 = Color(0xff0c0e12);
  static const Color alphaWhite5 = Color(0x0d0c0e12);
  static const Color alphaWhite2 = Color(0x050c0e12);
  static const Color alphaBlack5 = Color(0x0dffffff);
  static const Color alphaBlack2 = Color(0x05ffffff);
}

extension TokensX on BuildContext {
  Brightness get _b => Theme.of(this).brightness;

  Color get textPrimary900 => _b == Brightness.dark ? TokensDark.textPrimary900 : TokensLight.textPrimary900;
  Color get textTertiary600 => _b == Brightness.dark ? TokensDark.textTertiary600 : TokensLight.textTertiary600;
  Color get textErrorPrimary600 => _b == Brightness.dark ? TokensDark.textErrorPrimary600 : TokensLight.textErrorPrimary600;
  Color get textWarningPrimary600 => _b == Brightness.dark ? TokensDark.textWarningPrimary600 : TokensLight.textWarningPrimary600;
  Color get textSuccessPrimary600 => _b == Brightness.dark ? TokensDark.textSuccessPrimary600 : TokensLight.textSuccessPrimary600;
  Color get textWhite => _b == Brightness.dark ? TokensDark.textWhite : TokensLight.textWhite;
  Color get textSecondary700 => _b == Brightness.dark ? TokensDark.textSecondary700 : TokensLight.textSecondary700;
  Color get textDisabled => _b == Brightness.dark ? TokensDark.textDisabled : TokensLight.textDisabled;
  Color get textSecondaryHover => _b == Brightness.dark ? TokensDark.textSecondaryHover : TokensLight.textSecondaryHover;
  Color get textTertiaryHover => _b == Brightness.dark ? TokensDark.textTertiaryHover : TokensLight.textTertiaryHover;
  Color get textBrandSecondary700 => _b == Brightness.dark ? TokensDark.textBrandSecondary700 : TokensLight.textBrandSecondary700;
  Color get textPlaceholder => _b == Brightness.dark ? TokensDark.textPlaceholder : TokensLight.textPlaceholder;
  Color get textPlaceholderSubtle => _b == Brightness.dark ? TokensDark.textPlaceholderSubtle : TokensLight.textPlaceholderSubtle;
  Color get textBrandTertiary600 => _b == Brightness.dark ? TokensDark.textBrandTertiary600 : TokensLight.textBrandTertiary600;
  Color get textQuaternary500 => _b == Brightness.dark ? TokensDark.textQuaternary500 : TokensLight.textQuaternary500;
  Color get textBrandPrimary900 => _b == Brightness.dark ? TokensDark.textBrandPrimary900 : TokensLight.textBrandPrimary900;
  Color get textPrimaryOnBrand => _b == Brightness.dark ? TokensDark.textPrimaryOnBrand : TokensLight.textPrimaryOnBrand;
  Color get textSecondaryOnBrand => _b == Brightness.dark ? TokensDark.textSecondaryOnBrand : TokensLight.textSecondaryOnBrand;
  Color get textTertiaryOnBrand => _b == Brightness.dark ? TokensDark.textTertiaryOnBrand : TokensLight.textTertiaryOnBrand;
  Color get textQuaternaryOnBrand => _b == Brightness.dark ? TokensDark.textQuaternaryOnBrand : TokensLight.textQuaternaryOnBrand;
  Color get textBrandTertiaryAlt => _b == Brightness.dark ? TokensDark.textBrandTertiaryAlt : TokensLight.textBrandTertiaryAlt;
  Color get borderSecondary => _b == Brightness.dark ? TokensDark.borderSecondary : TokensLight.borderSecondary;
  Color get borderErrorSubtle => _b == Brightness.dark ? TokensDark.borderErrorSubtle : TokensLight.borderErrorSubtle;
  Color get borderPrimary => _b == Brightness.dark ? TokensDark.borderPrimary : TokensLight.borderPrimary;
  Color get borderBrand => _b == Brightness.dark ? TokensDark.borderBrand : TokensLight.borderBrand;
  Color get borderDisabled => _b == Brightness.dark ? TokensDark.borderDisabled : TokensLight.borderDisabled;
  Color get borderError => _b == Brightness.dark ? TokensDark.borderError : TokensLight.borderError;
  Color get borderDisabledSubtle => _b == Brightness.dark ? TokensDark.borderDisabledSubtle : TokensLight.borderDisabledSubtle;
  Color get borderTertiary => _b == Brightness.dark ? TokensDark.borderTertiary : TokensLight.borderTertiary;
  Color get borderBrandAlt => _b == Brightness.dark ? TokensDark.borderBrandAlt : TokensLight.borderBrandAlt;
  Color get bgPrimary => _b == Brightness.dark ? TokensDark.bgPrimary : TokensLight.bgPrimary;
  Color get bgTertiary => _b == Brightness.dark ? TokensDark.bgTertiary : TokensLight.bgTertiary;
  Color get bgBrandPrimary => _b == Brightness.dark ? TokensDark.bgBrandPrimary : TokensLight.bgBrandPrimary;
  Color get bgErrorSecondary => _b == Brightness.dark ? TokensDark.bgErrorSecondary : TokensLight.bgErrorSecondary;
  Color get bgWarningPrimary => _b == Brightness.dark ? TokensDark.bgWarningPrimary : TokensLight.bgWarningPrimary;
  Color get bgWarningSecondary => _b == Brightness.dark ? TokensDark.bgWarningSecondary : TokensLight.bgWarningSecondary;
  Color get bgSuccessPrimary => _b == Brightness.dark ? TokensDark.bgSuccessPrimary : TokensLight.bgSuccessPrimary;
  Color get bgSuccessSecondary => _b == Brightness.dark ? TokensDark.bgSuccessSecondary : TokensLight.bgSuccessSecondary;
  Color get bgBrandSolid => _b == Brightness.dark ? TokensDark.bgBrandSolid : TokensLight.bgBrandSolid;
  Color get bgSecondarySolid => _b == Brightness.dark ? TokensDark.bgSecondarySolid : TokensLight.bgSecondarySolid;
  Color get bgErrorSolid => _b == Brightness.dark ? TokensDark.bgErrorSolid : TokensLight.bgErrorSolid;
  Color get bgWarningSolid => _b == Brightness.dark ? TokensDark.bgWarningSolid : TokensLight.bgWarningSolid;
  Color get bgSuccessSolid => _b == Brightness.dark ? TokensDark.bgSuccessSolid : TokensLight.bgSuccessSolid;
  Color get bgSecondaryHover => _b == Brightness.dark ? TokensDark.bgSecondaryHover : TokensLight.bgSecondaryHover;
  Color get bgPrimaryHover => _b == Brightness.dark ? TokensDark.bgPrimaryHover : TokensLight.bgPrimaryHover;
  Color get bgDisabled => _b == Brightness.dark ? TokensDark.bgDisabled : TokensLight.bgDisabled;
  Color get bgActive => _b == Brightness.dark ? TokensDark.bgActive : TokensLight.bgActive;
  Color get bgBrandSolidHover => _b == Brightness.dark ? TokensDark.bgBrandSolidHover : TokensLight.bgBrandSolidHover;
  Color get bgErrorPrimary => _b == Brightness.dark ? TokensDark.bgErrorPrimary : TokensLight.bgErrorPrimary;
  Color get bgBrandSecondary => _b == Brightness.dark ? TokensDark.bgBrandSecondary : TokensLight.bgBrandSecondary;
  Color get bgSecondary => _b == Brightness.dark ? TokensDark.bgSecondary : TokensLight.bgSecondary;
  Color get bgDisabledSubtle => _b == Brightness.dark ? TokensDark.bgDisabledSubtle : TokensLight.bgDisabledSubtle;
  Color get bgQuaternary => _b == Brightness.dark ? TokensDark.bgQuaternary : TokensLight.bgQuaternary;
  Color get bgPrimaryAlt => _b == Brightness.dark ? TokensDark.bgPrimaryAlt : TokensLight.bgPrimaryAlt;
  Color get bgBrandPrimaryAlt => _b == Brightness.dark ? TokensDark.bgBrandPrimaryAlt : TokensLight.bgBrandPrimaryAlt;
  Color get bgSecondaryAlt => _b == Brightness.dark ? TokensDark.bgSecondaryAlt : TokensLight.bgSecondaryAlt;
  Color get bgOverlay => _b == Brightness.dark ? TokensDark.bgOverlay : TokensLight.bgOverlay;
  Color get bgSecondarySubtle => _b == Brightness.dark ? TokensDark.bgSecondarySubtle : TokensLight.bgSecondarySubtle;
  Color get bgBrandSection => _b == Brightness.dark ? TokensDark.bgBrandSection : TokensLight.bgBrandSection;
  Color get bgBrandSectionSubtle => _b == Brightness.dark ? TokensDark.bgBrandSectionSubtle : TokensLight.bgBrandSectionSubtle;
  Color get bgPrimarySolid => _b == Brightness.dark ? TokensDark.bgPrimarySolid : TokensLight.bgPrimarySolid;
  Color get bgMobileSign => _b == Brightness.dark ? TokensDark.bgMobileSign : TokensLight.bgMobileSign;
  Color get bgMobilePrimary => _b == Brightness.dark ? TokensDark.bgMobilePrimary : TokensLight.bgMobilePrimary;
  Color get fgSecondary700 => _b == Brightness.dark ? TokensDark.fgSecondary700 : TokensLight.fgSecondary700;
  Color get fgWarningPrimary => _b == Brightness.dark ? TokensDark.fgWarningPrimary : TokensLight.fgWarningPrimary;
  Color get fgSuccessPrimary => _b == Brightness.dark ? TokensDark.fgSuccessPrimary : TokensLight.fgSuccessPrimary;
  Color get fgWhite => _b == Brightness.dark ? TokensDark.fgWhite : TokensLight.fgWhite;
  Color get fgSuccessSecondary => _b == Brightness.dark ? TokensDark.fgSuccessSecondary : TokensLight.fgSuccessSecondary;
  Color get fgSecondaryHover => _b == Brightness.dark ? TokensDark.fgSecondaryHover : TokensLight.fgSecondaryHover;
  Color get fgPrimary900 => _b == Brightness.dark ? TokensDark.fgPrimary900 : TokensLight.fgPrimary900;
  Color get fgDisabled => _b == Brightness.dark ? TokensDark.fgDisabled : TokensLight.fgDisabled;
  Color get fgQuaternary500 => _b == Brightness.dark ? TokensDark.fgQuaternary500 : TokensLight.fgQuaternary500;
  Color get fgQuaternaryHover => _b == Brightness.dark ? TokensDark.fgQuaternaryHover : TokensLight.fgQuaternaryHover;
  Color get fgBrandSecondary500 => _b == Brightness.dark ? TokensDark.fgBrandSecondary500 : TokensLight.fgBrandSecondary500;
  Color get fgBrandPrimary => _b == Brightness.dark ? TokensDark.fgBrandPrimary : TokensLight.fgBrandPrimary;
  Color get fgQuinary400 => _b == Brightness.dark ? TokensDark.fgQuinary400 : TokensLight.fgQuinary400;
  Color get fgQuinaryHover => _b == Brightness.dark ? TokensDark.fgQuinaryHover : TokensLight.fgQuinaryHover;
  Color get fgErrorPrimary => _b == Brightness.dark ? TokensDark.fgErrorPrimary : TokensLight.fgErrorPrimary;
  Color get fgDisabledSubtle => _b == Brightness.dark ? TokensDark.fgDisabledSubtle : TokensLight.fgDisabledSubtle;
  Color get fgWarningSecondary => _b == Brightness.dark ? TokensDark.fgWarningSecondary : TokensLight.fgWarningSecondary;
  Color get fgErrorSecondary => _b == Brightness.dark ? TokensDark.fgErrorSecondary : TokensLight.fgErrorSecondary;
  Color get fgSenary300 => _b == Brightness.dark ? TokensDark.fgSenary300 : TokensLight.fgSenary300;
  Color get fgTertiary600 => _b == Brightness.dark ? TokensDark.fgTertiary600 : TokensLight.fgTertiary600;
  Color get fgTertiaryHover => _b == Brightness.dark ? TokensDark.fgTertiaryHover : TokensLight.fgTertiaryHover;
  Color get fgBrandPrimaryAlt => _b == Brightness.dark ? TokensDark.fgBrandPrimaryAlt : TokensLight.fgBrandPrimaryAlt;
  Color get shadowXs => _b == Brightness.dark ? TokensDark.shadowXs : TokensLight.shadowXs;
  Color get shadowSm02 => _b == Brightness.dark ? TokensDark.shadowSm02 : TokensLight.shadowSm02;
  Color get shadowLg01 => _b == Brightness.dark ? TokensDark.shadowLg01 : TokensLight.shadowLg01;
  Color get shadowLg02 => _b == Brightness.dark ? TokensDark.shadowLg02 : TokensLight.shadowLg02;
  Color get shadowSm01 => _b == Brightness.dark ? TokensDark.shadowSm01 : TokensLight.shadowSm01;
  Color get shadow3xl01 => _b == Brightness.dark ? TokensDark.shadow3xl01 : TokensLight.shadow3xl01;
  Color get shadow2xl01 => _b == Brightness.dark ? TokensDark.shadow2xl01 : TokensLight.shadow2xl01;
  Color get shadowMd01 => _b == Brightness.dark ? TokensDark.shadowMd01 : TokensLight.shadowMd01;
  Color get shadowMd02 => _b == Brightness.dark ? TokensDark.shadowMd02 : TokensLight.shadowMd02;
  Color get shadowXl01 => _b == Brightness.dark ? TokensDark.shadowXl01 : TokensLight.shadowXl01;
  Color get shadowXl02 => _b == Brightness.dark ? TokensDark.shadowXl02 : TokensLight.shadowXl02;
  Color get shadowSkeumorphicInner => _b == Brightness.dark ? TokensDark.shadowSkeumorphicInner : TokensLight.shadowSkeumorphicInner;
  Color get shadowSkeumorphicInnerBorder => _b == Brightness.dark ? TokensDark.shadowSkeumorphicInnerBorder : TokensLight.shadowSkeumorphicInnerBorder;
  Color get shadowLg03 => _b == Brightness.dark ? TokensDark.shadowLg03 : TokensLight.shadowLg03;
  Color get shadowXl03 => _b == Brightness.dark ? TokensDark.shadowXl03 : TokensLight.shadowXl03;
  Color get shadow2xl02 => _b == Brightness.dark ? TokensDark.shadow2xl02 : TokensLight.shadow2xl02;
  Color get shadow3xl02 => _b == Brightness.dark ? TokensDark.shadow3xl02 : TokensLight.shadow3xl02;
  Color get shadowMainCentreMd => _b == Brightness.dark ? TokensDark.shadowMainCentreMd : TokensLight.shadowMainCentreMd;
  Color get shadowMainCentreLg => _b == Brightness.dark ? TokensDark.shadowMainCentreLg : TokensLight.shadowMainCentreLg;
  Color get shadowOverlayLg => _b == Brightness.dark ? TokensDark.shadowOverlayLg : TokensLight.shadowOverlayLg;
  Color get shadowGridMd => _b == Brightness.dark ? TokensDark.shadowGridMd : TokensLight.shadowGridMd;
  Color get focusRing => _b == Brightness.dark ? TokensDark.focusRing : TokensLight.focusRing;
  Color get focusRingError => _b == Brightness.dark ? TokensDark.focusRingError : TokensLight.focusRingError;
  Color get utilityBlue600 => _b == Brightness.dark ? TokensDark.utilityBlue600 : TokensLight.utilityBlue600;
  Color get utilityBlue700 => _b == Brightness.dark ? TokensDark.utilityBlue700 : TokensLight.utilityBlue700;
  Color get utilityBlue500 => _b == Brightness.dark ? TokensDark.utilityBlue500 : TokensLight.utilityBlue500;
  Color get utilityBlue200 => _b == Brightness.dark ? TokensDark.utilityBlue200 : TokensLight.utilityBlue200;
  Color get utilityBlue50 => _b == Brightness.dark ? TokensDark.utilityBlue50 : TokensLight.utilityBlue50;
  Color get utilityBlue100 => _b == Brightness.dark ? TokensDark.utilityBlue100 : TokensLight.utilityBlue100;
  Color get utilityBlue400 => _b == Brightness.dark ? TokensDark.utilityBlue400 : TokensLight.utilityBlue400;
  Color get utilityBlue300 => _b == Brightness.dark ? TokensDark.utilityBlue300 : TokensLight.utilityBlue300;
  Color get utilityBrand600 => _b == Brightness.dark ? TokensDark.utilityBrand600 : TokensLight.utilityBrand600;
  Color get utilityBrand700 => _b == Brightness.dark ? TokensDark.utilityBrand700 : TokensLight.utilityBrand700;
  Color get utilityBrand500 => _b == Brightness.dark ? TokensDark.utilityBrand500 : TokensLight.utilityBrand500;
  Color get utilityBrand200 => _b == Brightness.dark ? TokensDark.utilityBrand200 : TokensLight.utilityBrand200;
  Color get utilityBrand50 => _b == Brightness.dark ? TokensDark.utilityBrand50 : TokensLight.utilityBrand50;
  Color get utilityBrand100 => _b == Brightness.dark ? TokensDark.utilityBrand100 : TokensLight.utilityBrand100;
  Color get utilityBrand400 => _b == Brightness.dark ? TokensDark.utilityBrand400 : TokensLight.utilityBrand400;
  Color get utilityBrand50Alt => _b == Brightness.dark ? TokensDark.utilityBrand50Alt : TokensLight.utilityBrand50Alt;
  Color get utilityBrand100Alt => _b == Brightness.dark ? TokensDark.utilityBrand100Alt : TokensLight.utilityBrand100Alt;
  Color get utilityBrand200Alt => _b == Brightness.dark ? TokensDark.utilityBrand200Alt : TokensLight.utilityBrand200Alt;
  Color get utilityBrand400Alt => _b == Brightness.dark ? TokensDark.utilityBrand400Alt : TokensLight.utilityBrand400Alt;
  Color get utilityBrand500Alt => _b == Brightness.dark ? TokensDark.utilityBrand500Alt : TokensLight.utilityBrand500Alt;
  Color get utilityBrand600Alt => _b == Brightness.dark ? TokensDark.utilityBrand600Alt : TokensLight.utilityBrand600Alt;
  Color get utilityBrand700Alt => _b == Brightness.dark ? TokensDark.utilityBrand700Alt : TokensLight.utilityBrand700Alt;
  Color get utilityBrand300 => _b == Brightness.dark ? TokensDark.utilityBrand300 : TokensLight.utilityBrand300;
  Color get utilityBrand900 => _b == Brightness.dark ? TokensDark.utilityBrand900 : TokensLight.utilityBrand900;
  Color get utilityBrand800 => _b == Brightness.dark ? TokensDark.utilityBrand800 : TokensLight.utilityBrand800;
  Color get utilityBrand300Alt => _b == Brightness.dark ? TokensDark.utilityBrand300Alt : TokensLight.utilityBrand300Alt;
  Color get utilityBrand800Alt => _b == Brightness.dark ? TokensDark.utilityBrand800Alt : TokensLight.utilityBrand800Alt;
  Color get utilityBrand900Alt => _b == Brightness.dark ? TokensDark.utilityBrand900Alt : TokensLight.utilityBrand900Alt;
  Color get utilityGray700 => _b == Brightness.dark ? TokensDark.utilityGray700 : TokensLight.utilityGray700;
  Color get utilityGray600 => _b == Brightness.dark ? TokensDark.utilityGray600 : TokensLight.utilityGray600;
  Color get utilityGray500 => _b == Brightness.dark ? TokensDark.utilityGray500 : TokensLight.utilityGray500;
  Color get utilityGray200 => _b == Brightness.dark ? TokensDark.utilityGray200 : TokensLight.utilityGray200;
  Color get utilityGray50 => _b == Brightness.dark ? TokensDark.utilityGray50 : TokensLight.utilityGray50;
  Color get utilityGray100 => _b == Brightness.dark ? TokensDark.utilityGray100 : TokensLight.utilityGray100;
  Color get utilityGray400 => _b == Brightness.dark ? TokensDark.utilityGray400 : TokensLight.utilityGray400;
  Color get utilityGray300 => _b == Brightness.dark ? TokensDark.utilityGray300 : TokensLight.utilityGray300;
  Color get utilityGray900 => _b == Brightness.dark ? TokensDark.utilityGray900 : TokensLight.utilityGray900;
  Color get utilityGray800 => _b == Brightness.dark ? TokensDark.utilityGray800 : TokensLight.utilityGray800;
  Color get utilityError600 => _b == Brightness.dark ? TokensDark.utilityError600 : TokensLight.utilityError600;
  Color get utilityError700 => _b == Brightness.dark ? TokensDark.utilityError700 : TokensLight.utilityError700;
  Color get utilityError500 => _b == Brightness.dark ? TokensDark.utilityError500 : TokensLight.utilityError500;
  Color get utilityError200 => _b == Brightness.dark ? TokensDark.utilityError200 : TokensLight.utilityError200;
  Color get utilityError50 => _b == Brightness.dark ? TokensDark.utilityError50 : TokensLight.utilityError50;
  Color get utilityError100 => _b == Brightness.dark ? TokensDark.utilityError100 : TokensLight.utilityError100;
  Color get utilityError400 => _b == Brightness.dark ? TokensDark.utilityError400 : TokensLight.utilityError400;
  Color get utilityError300 => _b == Brightness.dark ? TokensDark.utilityError300 : TokensLight.utilityError300;
  Color get utilityWarning600 => _b == Brightness.dark ? TokensDark.utilityWarning600 : TokensLight.utilityWarning600;
  Color get utilityWarning700 => _b == Brightness.dark ? TokensDark.utilityWarning700 : TokensLight.utilityWarning700;
  Color get utilityWarning500 => _b == Brightness.dark ? TokensDark.utilityWarning500 : TokensLight.utilityWarning500;
  Color get utilityWarning200 => _b == Brightness.dark ? TokensDark.utilityWarning200 : TokensLight.utilityWarning200;
  Color get utilityWarning50 => _b == Brightness.dark ? TokensDark.utilityWarning50 : TokensLight.utilityWarning50;
  Color get utilityWarning100 => _b == Brightness.dark ? TokensDark.utilityWarning100 : TokensLight.utilityWarning100;
  Color get utilityWarning400 => _b == Brightness.dark ? TokensDark.utilityWarning400 : TokensLight.utilityWarning400;
  Color get utilityWarning300 => _b == Brightness.dark ? TokensDark.utilityWarning300 : TokensLight.utilityWarning300;
  Color get utilitySuccess600 => _b == Brightness.dark ? TokensDark.utilitySuccess600 : TokensLight.utilitySuccess600;
  Color get utilitySuccess700 => _b == Brightness.dark ? TokensDark.utilitySuccess700 : TokensLight.utilitySuccess700;
  Color get utilitySuccess500 => _b == Brightness.dark ? TokensDark.utilitySuccess500 : TokensLight.utilitySuccess500;
  Color get utilitySuccess200 => _b == Brightness.dark ? TokensDark.utilitySuccess200 : TokensLight.utilitySuccess200;
  Color get utilitySuccess50 => _b == Brightness.dark ? TokensDark.utilitySuccess50 : TokensLight.utilitySuccess50;
  Color get utilitySuccess100 => _b == Brightness.dark ? TokensDark.utilitySuccess100 : TokensLight.utilitySuccess100;
  Color get utilitySuccess400 => _b == Brightness.dark ? TokensDark.utilitySuccess400 : TokensLight.utilitySuccess400;
  Color get utilitySuccess300 => _b == Brightness.dark ? TokensDark.utilitySuccess300 : TokensLight.utilitySuccess300;
  Color get utilityOrange600 => _b == Brightness.dark ? TokensDark.utilityOrange600 : TokensLight.utilityOrange600;
  Color get utilityOrange700 => _b == Brightness.dark ? TokensDark.utilityOrange700 : TokensLight.utilityOrange700;
  Color get utilityOrange500 => _b == Brightness.dark ? TokensDark.utilityOrange500 : TokensLight.utilityOrange500;
  Color get utilityOrange200 => _b == Brightness.dark ? TokensDark.utilityOrange200 : TokensLight.utilityOrange200;
  Color get utilityOrange50 => _b == Brightness.dark ? TokensDark.utilityOrange50 : TokensLight.utilityOrange50;
  Color get utilityOrange100 => _b == Brightness.dark ? TokensDark.utilityOrange100 : TokensLight.utilityOrange100;
  Color get utilityOrange400 => _b == Brightness.dark ? TokensDark.utilityOrange400 : TokensLight.utilityOrange400;
  Color get utilityOrange300 => _b == Brightness.dark ? TokensDark.utilityOrange300 : TokensLight.utilityOrange300;
  Color get utilityBlueDark600 => _b == Brightness.dark ? TokensDark.utilityBlueDark600 : TokensLight.utilityBlueDark600;
  Color get utilityBlueDark700 => _b == Brightness.dark ? TokensDark.utilityBlueDark700 : TokensLight.utilityBlueDark700;
  Color get utilityBlueDark500 => _b == Brightness.dark ? TokensDark.utilityBlueDark500 : TokensLight.utilityBlueDark500;
  Color get utilityBlueDark200 => _b == Brightness.dark ? TokensDark.utilityBlueDark200 : TokensLight.utilityBlueDark200;
  Color get utilityBlueDark50 => _b == Brightness.dark ? TokensDark.utilityBlueDark50 : TokensLight.utilityBlueDark50;
  Color get utilityBlueDark100 => _b == Brightness.dark ? TokensDark.utilityBlueDark100 : TokensLight.utilityBlueDark100;
  Color get utilityBlueDark400 => _b == Brightness.dark ? TokensDark.utilityBlueDark400 : TokensLight.utilityBlueDark400;
  Color get utilityBlueDark300 => _b == Brightness.dark ? TokensDark.utilityBlueDark300 : TokensLight.utilityBlueDark300;
  Color get utilityIndigo600 => _b == Brightness.dark ? TokensDark.utilityIndigo600 : TokensLight.utilityIndigo600;
  Color get utilityIndigo700 => _b == Brightness.dark ? TokensDark.utilityIndigo700 : TokensLight.utilityIndigo700;
  Color get utilityIndigo500 => _b == Brightness.dark ? TokensDark.utilityIndigo500 : TokensLight.utilityIndigo500;
  Color get utilityIndigo200 => _b == Brightness.dark ? TokensDark.utilityIndigo200 : TokensLight.utilityIndigo200;
  Color get utilityIndigo50 => _b == Brightness.dark ? TokensDark.utilityIndigo50 : TokensLight.utilityIndigo50;
  Color get utilityIndigo100 => _b == Brightness.dark ? TokensDark.utilityIndigo100 : TokensLight.utilityIndigo100;
  Color get utilityIndigo400 => _b == Brightness.dark ? TokensDark.utilityIndigo400 : TokensLight.utilityIndigo400;
  Color get utilityIndigo300 => _b == Brightness.dark ? TokensDark.utilityIndigo300 : TokensLight.utilityIndigo300;
  Color get utilityFuchsia600 => _b == Brightness.dark ? TokensDark.utilityFuchsia600 : TokensLight.utilityFuchsia600;
  Color get utilityFuchsia700 => _b == Brightness.dark ? TokensDark.utilityFuchsia700 : TokensLight.utilityFuchsia700;
  Color get utilityFuchsia500 => _b == Brightness.dark ? TokensDark.utilityFuchsia500 : TokensLight.utilityFuchsia500;
  Color get utilityFuchsia200 => _b == Brightness.dark ? TokensDark.utilityFuchsia200 : TokensLight.utilityFuchsia200;
  Color get utilityFuchsia50 => _b == Brightness.dark ? TokensDark.utilityFuchsia50 : TokensLight.utilityFuchsia50;
  Color get utilityFuchsia100 => _b == Brightness.dark ? TokensDark.utilityFuchsia100 : TokensLight.utilityFuchsia100;
  Color get utilityFuchsia400 => _b == Brightness.dark ? TokensDark.utilityFuchsia400 : TokensLight.utilityFuchsia400;
  Color get utilityFuchsia300 => _b == Brightness.dark ? TokensDark.utilityFuchsia300 : TokensLight.utilityFuchsia300;
  Color get utilityPink600 => _b == Brightness.dark ? TokensDark.utilityPink600 : TokensLight.utilityPink600;
  Color get utilityPink700 => _b == Brightness.dark ? TokensDark.utilityPink700 : TokensLight.utilityPink700;
  Color get utilityPink500 => _b == Brightness.dark ? TokensDark.utilityPink500 : TokensLight.utilityPink500;
  Color get utilityPink200 => _b == Brightness.dark ? TokensDark.utilityPink200 : TokensLight.utilityPink200;
  Color get utilityPink50 => _b == Brightness.dark ? TokensDark.utilityPink50 : TokensLight.utilityPink50;
  Color get utilityPink100 => _b == Brightness.dark ? TokensDark.utilityPink100 : TokensLight.utilityPink100;
  Color get utilityPink400 => _b == Brightness.dark ? TokensDark.utilityPink400 : TokensLight.utilityPink400;
  Color get utilityPink300 => _b == Brightness.dark ? TokensDark.utilityPink300 : TokensLight.utilityPink300;
  Color get utilityPurple600 => _b == Brightness.dark ? TokensDark.utilityPurple600 : TokensLight.utilityPurple600;
  Color get utilityPurple700 => _b == Brightness.dark ? TokensDark.utilityPurple700 : TokensLight.utilityPurple700;
  Color get utilityPurple500 => _b == Brightness.dark ? TokensDark.utilityPurple500 : TokensLight.utilityPurple500;
  Color get utilityPurple200 => _b == Brightness.dark ? TokensDark.utilityPurple200 : TokensLight.utilityPurple200;
  Color get utilityPurple50 => _b == Brightness.dark ? TokensDark.utilityPurple50 : TokensLight.utilityPurple50;
  Color get utilityPurple100 => _b == Brightness.dark ? TokensDark.utilityPurple100 : TokensLight.utilityPurple100;
  Color get utilityPurple400 => _b == Brightness.dark ? TokensDark.utilityPurple400 : TokensLight.utilityPurple400;
  Color get utilityPurple300 => _b == Brightness.dark ? TokensDark.utilityPurple300 : TokensLight.utilityPurple300;
  Color get utilityOrangeDark600 => _b == Brightness.dark ? TokensDark.utilityOrangeDark600 : TokensLight.utilityOrangeDark600;
  Color get utilityOrangeDark700 => _b == Brightness.dark ? TokensDark.utilityOrangeDark700 : TokensLight.utilityOrangeDark700;
  Color get utilityOrangeDark500 => _b == Brightness.dark ? TokensDark.utilityOrangeDark500 : TokensLight.utilityOrangeDark500;
  Color get utilityOrangeDark200 => _b == Brightness.dark ? TokensDark.utilityOrangeDark200 : TokensLight.utilityOrangeDark200;
  Color get utilityOrangeDark50 => _b == Brightness.dark ? TokensDark.utilityOrangeDark50 : TokensLight.utilityOrangeDark50;
  Color get utilityOrangeDark100 => _b == Brightness.dark ? TokensDark.utilityOrangeDark100 : TokensLight.utilityOrangeDark100;
  Color get utilityOrangeDark400 => _b == Brightness.dark ? TokensDark.utilityOrangeDark400 : TokensLight.utilityOrangeDark400;
  Color get utilityOrangeDark300 => _b == Brightness.dark ? TokensDark.utilityOrangeDark300 : TokensLight.utilityOrangeDark300;
  Color get utilityBlueLight600 => _b == Brightness.dark ? TokensDark.utilityBlueLight600 : TokensLight.utilityBlueLight600;
  Color get utilityBlueLight700 => _b == Brightness.dark ? TokensDark.utilityBlueLight700 : TokensLight.utilityBlueLight700;
  Color get utilityBlueLight500 => _b == Brightness.dark ? TokensDark.utilityBlueLight500 : TokensLight.utilityBlueLight500;
  Color get utilityBlueLight200 => _b == Brightness.dark ? TokensDark.utilityBlueLight200 : TokensLight.utilityBlueLight200;
  Color get utilityBlueLight50 => _b == Brightness.dark ? TokensDark.utilityBlueLight50 : TokensLight.utilityBlueLight50;
  Color get utilityBlueLight100 => _b == Brightness.dark ? TokensDark.utilityBlueLight100 : TokensLight.utilityBlueLight100;
  Color get utilityBlueLight400 => _b == Brightness.dark ? TokensDark.utilityBlueLight400 : TokensLight.utilityBlueLight400;
  Color get utilityBlueLight300 => _b == Brightness.dark ? TokensDark.utilityBlueLight300 : TokensLight.utilityBlueLight300;
  Color get utilityGrayBlue600 => _b == Brightness.dark ? TokensDark.utilityGrayBlue600 : TokensLight.utilityGrayBlue600;
  Color get utilityGrayBlue700 => _b == Brightness.dark ? TokensDark.utilityGrayBlue700 : TokensLight.utilityGrayBlue700;
  Color get utilityGrayBlue500 => _b == Brightness.dark ? TokensDark.utilityGrayBlue500 : TokensLight.utilityGrayBlue500;
  Color get utilityGrayBlue200 => _b == Brightness.dark ? TokensDark.utilityGrayBlue200 : TokensLight.utilityGrayBlue200;
  Color get utilityGrayBlue50 => _b == Brightness.dark ? TokensDark.utilityGrayBlue50 : TokensLight.utilityGrayBlue50;
  Color get utilityGrayBlue100 => _b == Brightness.dark ? TokensDark.utilityGrayBlue100 : TokensLight.utilityGrayBlue100;
  Color get utilityGrayBlue400 => _b == Brightness.dark ? TokensDark.utilityGrayBlue400 : TokensLight.utilityGrayBlue400;
  Color get utilityGrayBlue300 => _b == Brightness.dark ? TokensDark.utilityGrayBlue300 : TokensLight.utilityGrayBlue300;
  Color get utilityGreen50 => _b == Brightness.dark ? TokensDark.utilityGreen50 : TokensLight.utilityGreen50;
  Color get utilityGreen100 => _b == Brightness.dark ? TokensDark.utilityGreen100 : TokensLight.utilityGreen100;
  Color get utilityGreen200 => _b == Brightness.dark ? TokensDark.utilityGreen200 : TokensLight.utilityGreen200;
  Color get utilityGreen300 => _b == Brightness.dark ? TokensDark.utilityGreen300 : TokensLight.utilityGreen300;
  Color get utilityGreen400 => _b == Brightness.dark ? TokensDark.utilityGreen400 : TokensLight.utilityGreen400;
  Color get utilityGreen500 => _b == Brightness.dark ? TokensDark.utilityGreen500 : TokensLight.utilityGreen500;
  Color get utilityGreen600 => _b == Brightness.dark ? TokensDark.utilityGreen600 : TokensLight.utilityGreen600;
  Color get utilityGreen700 => _b == Brightness.dark ? TokensDark.utilityGreen700 : TokensLight.utilityGreen700;
  Color get utilityYellow50 => _b == Brightness.dark ? TokensDark.utilityYellow50 : TokensLight.utilityYellow50;
  Color get utilityYellow100 => _b == Brightness.dark ? TokensDark.utilityYellow100 : TokensLight.utilityYellow100;
  Color get utilityYellow200 => _b == Brightness.dark ? TokensDark.utilityYellow200 : TokensLight.utilityYellow200;
  Color get utilityYellow300 => _b == Brightness.dark ? TokensDark.utilityYellow300 : TokensLight.utilityYellow300;
  Color get utilityYellow400 => _b == Brightness.dark ? TokensDark.utilityYellow400 : TokensLight.utilityYellow400;
  Color get utilityYellow500 => _b == Brightness.dark ? TokensDark.utilityYellow500 : TokensLight.utilityYellow500;
  Color get utilityYellow600 => _b == Brightness.dark ? TokensDark.utilityYellow600 : TokensLight.utilityYellow600;
  Color get utilityYellow700 => _b == Brightness.dark ? TokensDark.utilityYellow700 : TokensLight.utilityYellow700;
  Color get tooltipSupportingText => _b == Brightness.dark ? TokensDark.tooltipSupportingText : TokensLight.tooltipSupportingText;
  Color get buttonPrimaryBg => _b == Brightness.dark ? TokensDark.buttonPrimaryBg : TokensLight.buttonPrimaryBg;
  Color get buttonPrimaryBgHover => _b == Brightness.dark ? TokensDark.buttonPrimaryBgHover : TokensLight.buttonPrimaryBgHover;
  Color get buttonPrimaryFg => _b == Brightness.dark ? TokensDark.buttonPrimaryFg : TokensLight.buttonPrimaryFg;
  Color get buttonPrimaryFgHover => _b == Brightness.dark ? TokensDark.buttonPrimaryFgHover : TokensLight.buttonPrimaryFgHover;
  Color get buttonSecondaryBg => _b == Brightness.dark ? TokensDark.buttonSecondaryBg : TokensLight.buttonSecondaryBg;
  Color get buttonSecondaryBgHover => _b == Brightness.dark ? TokensDark.buttonSecondaryBgHover : TokensLight.buttonSecondaryBgHover;
  Color get buttonSecondaryFg => _b == Brightness.dark ? TokensDark.buttonSecondaryFg : TokensLight.buttonSecondaryFg;
  Color get buttonSecondaryFgHover => _b == Brightness.dark ? TokensDark.buttonSecondaryFgHover : TokensLight.buttonSecondaryFgHover;
  Color get buttonSecondaryBorder => _b == Brightness.dark ? TokensDark.buttonSecondaryBorder : TokensLight.buttonSecondaryBorder;
  Color get buttonSecondaryBorderHover => _b == Brightness.dark ? TokensDark.buttonSecondaryBorderHover : TokensLight.buttonSecondaryBorderHover;
  Color get buttonSecondaryColorBg => _b == Brightness.dark ? TokensDark.buttonSecondaryColorBg : TokensLight.buttonSecondaryColorBg;
  Color get buttonSecondaryColorBgHover => _b == Brightness.dark ? TokensDark.buttonSecondaryColorBgHover : TokensLight.buttonSecondaryColorBgHover;
  Color get buttonSecondaryColorBorderHover => _b == Brightness.dark ? TokensDark.buttonSecondaryColorBorderHover : TokensLight.buttonSecondaryColorBorderHover;
  Color get buttonSecondaryColorBorder => _b == Brightness.dark ? TokensDark.buttonSecondaryColorBorder : TokensLight.buttonSecondaryColorBorder;
  Color get buttonSecondaryColorFg => _b == Brightness.dark ? TokensDark.buttonSecondaryColorFg : TokensLight.buttonSecondaryColorFg;
  Color get buttonSecondaryColorFgHover => _b == Brightness.dark ? TokensDark.buttonSecondaryColorFgHover : TokensLight.buttonSecondaryColorFgHover;
  Color get buttonPrimaryErrorFg => _b == Brightness.dark ? TokensDark.buttonPrimaryErrorFg : TokensLight.buttonPrimaryErrorFg;
  Color get buttonPrimaryErrorFgHover => _b == Brightness.dark ? TokensDark.buttonPrimaryErrorFgHover : TokensLight.buttonPrimaryErrorFgHover;
  Color get buttonPrimaryErrorBg => _b == Brightness.dark ? TokensDark.buttonPrimaryErrorBg : TokensLight.buttonPrimaryErrorBg;
  Color get buttonPrimaryErrorBgHover => _b == Brightness.dark ? TokensDark.buttonPrimaryErrorBgHover : TokensLight.buttonPrimaryErrorBgHover;
  Color get buttonSecondaryErrorFg => _b == Brightness.dark ? TokensDark.buttonSecondaryErrorFg : TokensLight.buttonSecondaryErrorFg;
  Color get buttonSecondaryErrorFgHover => _b == Brightness.dark ? TokensDark.buttonSecondaryErrorFgHover : TokensLight.buttonSecondaryErrorFgHover;
  Color get buttonSecondaryErrorBg => _b == Brightness.dark ? TokensDark.buttonSecondaryErrorBg : TokensLight.buttonSecondaryErrorBg;
  Color get buttonSecondaryErrorBgHover => _b == Brightness.dark ? TokensDark.buttonSecondaryErrorBgHover : TokensLight.buttonSecondaryErrorBgHover;
  Color get buttonSecondaryErrorBorder => _b == Brightness.dark ? TokensDark.buttonSecondaryErrorBorder : TokensLight.buttonSecondaryErrorBorder;
  Color get buttonSecondaryErrorBorderHover => _b == Brightness.dark ? TokensDark.buttonSecondaryErrorBorderHover : TokensLight.buttonSecondaryErrorBorderHover;
  Color get buttonTertiaryFg => _b == Brightness.dark ? TokensDark.buttonTertiaryFg : TokensLight.buttonTertiaryFg;
  Color get buttonTertiaryFgHover => _b == Brightness.dark ? TokensDark.buttonTertiaryFgHover : TokensLight.buttonTertiaryFgHover;
  Color get buttonTertiaryBgHover => _b == Brightness.dark ? TokensDark.buttonTertiaryBgHover : TokensLight.buttonTertiaryBgHover;
  Color get buttonTertiaryColorFg => _b == Brightness.dark ? TokensDark.buttonTertiaryColorFg : TokensLight.buttonTertiaryColorFg;
  Color get buttonTertiaryColorFgHover => _b == Brightness.dark ? TokensDark.buttonTertiaryColorFgHover : TokensLight.buttonTertiaryColorFgHover;
  Color get buttonTertiaryColorBgHover => _b == Brightness.dark ? TokensDark.buttonTertiaryColorBgHover : TokensLight.buttonTertiaryColorBgHover;
  Color get buttonTertiaryErrorFg => _b == Brightness.dark ? TokensDark.buttonTertiaryErrorFg : TokensLight.buttonTertiaryErrorFg;
  Color get buttonTertiaryErrorFgHover => _b == Brightness.dark ? TokensDark.buttonTertiaryErrorFgHover : TokensLight.buttonTertiaryErrorFgHover;
  Color get buttonTertiaryErrorBgHover => _b == Brightness.dark ? TokensDark.buttonTertiaryErrorBgHover : TokensLight.buttonTertiaryErrorBgHover;
  Color get buttonOutlineFg => _b == Brightness.dark ? TokensDark.buttonOutlineFg : TokensLight.buttonOutlineFg;
  Color get buttonOutlineFgHover => _b == Brightness.dark ? TokensDark.buttonOutlineFgHover : TokensLight.buttonOutlineFgHover;
  Color get buttonOutlineBg => _b == Brightness.dark ? TokensDark.buttonOutlineBg : TokensLight.buttonOutlineBg;
  Color get buttonOutlineBgHover => _b == Brightness.dark ? TokensDark.buttonOutlineBgHover : TokensLight.buttonOutlineBgHover;
  Color get buttonOutlineBorder => _b == Brightness.dark ? TokensDark.buttonOutlineBorder : TokensLight.buttonOutlineBorder;
  Color get buttonOutlineBorderHover => _b == Brightness.dark ? TokensDark.buttonOutlineBorderHover : TokensLight.buttonOutlineBorderHover;
  Color get wysiwygEditorIconFg => _b == Brightness.dark ? TokensDark.wysiwygEditorIconFg : TokensLight.wysiwygEditorIconFg;
  Color get wysiwygEditorIconFgActive => _b == Brightness.dark ? TokensDark.wysiwygEditorIconFgActive : TokensLight.wysiwygEditorIconFgActive;
  Color get avatarContrastBorder => _b == Brightness.dark ? TokensDark.avatarContrastBorder : TokensLight.avatarContrastBorder;
  Color get avatarProfilePhotoBorder => _b == Brightness.dark ? TokensDark.avatarProfilePhotoBorder : TokensLight.avatarProfilePhotoBorder;
  Color get avatarBg => _b == Brightness.dark ? TokensDark.avatarBg : TokensLight.avatarBg;
  Color get avatarStylesBgNeutral => _b == Brightness.dark ? TokensDark.avatarStylesBgNeutral : TokensLight.avatarStylesBgNeutral;
  Color get breadcrumbFg => _b == Brightness.dark ? TokensDark.breadcrumbFg : TokensLight.breadcrumbFg;
  Color get breadcrumbFgHover => _b == Brightness.dark ? TokensDark.breadcrumbFgHover : TokensLight.breadcrumbFgHover;
  Color get breadcrumbBgHover => _b == Brightness.dark ? TokensDark.breadcrumbBgHover : TokensLight.breadcrumbBgHover;
  Color get breadcrumbBrandBgHover => _b == Brightness.dark ? TokensDark.breadcrumbBrandBgHover : TokensLight.breadcrumbBrandBgHover;
  Color get breadcrumbBrandFgHover => _b == Brightness.dark ? TokensDark.breadcrumbBrandFgHover : TokensLight.breadcrumbBrandFgHover;
  Color get breadcrumbIconFg => _b == Brightness.dark ? TokensDark.breadcrumbIconFg : TokensLight.breadcrumbIconFg;
  Color get breadcrumbIconFgHover => _b == Brightness.dark ? TokensDark.breadcrumbIconFgHover : TokensLight.breadcrumbIconFgHover;
  Color get breadcrumbBrandIconFgHover => _b == Brightness.dark ? TokensDark.breadcrumbBrandIconFgHover : TokensLight.breadcrumbBrandIconFgHover;
  Color get featuredIconModernBorder => _b == Brightness.dark ? TokensDark.featuredIconModernBorder : TokensLight.featuredIconModernBorder;
  Color get featuredIconLightFgBrand => _b == Brightness.dark ? TokensDark.featuredIconLightFgBrand : TokensLight.featuredIconLightFgBrand;
  Color get featuredIconLightFgGray => _b == Brightness.dark ? TokensDark.featuredIconLightFgGray : TokensLight.featuredIconLightFgGray;
  Color get featuredIconLightFgError => _b == Brightness.dark ? TokensDark.featuredIconLightFgError : TokensLight.featuredIconLightFgError;
  Color get featuredIconLightFgWarning => _b == Brightness.dark ? TokensDark.featuredIconLightFgWarning : TokensLight.featuredIconLightFgWarning;
  Color get featuredIconLightFgSuccess => _b == Brightness.dark ? TokensDark.featuredIconLightFgSuccess : TokensLight.featuredIconLightFgSuccess;
  Color get featuredIconDarkFgBrand => _b == Brightness.dark ? TokensDark.featuredIconDarkFgBrand : TokensLight.featuredIconDarkFgBrand;
  Color get featuredIconDarkFgGray => _b == Brightness.dark ? TokensDark.featuredIconDarkFgGray : TokensLight.featuredIconDarkFgGray;
  Color get featuredIconDarkFgError => _b == Brightness.dark ? TokensDark.featuredIconDarkFgError : TokensLight.featuredIconDarkFgError;
  Color get featuredIconDarkFgWarning => _b == Brightness.dark ? TokensDark.featuredIconDarkFgWarning : TokensLight.featuredIconDarkFgWarning;
  Color get featuredIconDarkFgSuccess => _b == Brightness.dark ? TokensDark.featuredIconDarkFgSuccess : TokensLight.featuredIconDarkFgSuccess;
  Color get iconFgBrand => _b == Brightness.dark ? TokensDark.iconFgBrand : TokensLight.iconFgBrand;
  Color get iconFgBrandOnBrand => _b == Brightness.dark ? TokensDark.iconFgBrandOnBrand : TokensLight.iconFgBrandOnBrand;
  Color get socialIconFgX => _b == Brightness.dark ? TokensDark.socialIconFgX : TokensLight.socialIconFgX;
  Color get socialIconFgApple => _b == Brightness.dark ? TokensDark.socialIconFgApple : TokensLight.socialIconFgApple;
  Color get socialIconFgGithub => _b == Brightness.dark ? TokensDark.socialIconFgGithub : TokensLight.socialIconFgGithub;
  Color get socialIconFgAngellist => _b == Brightness.dark ? TokensDark.socialIconFgAngellist : TokensLight.socialIconFgAngellist;
  Color get socialIconFgTumblr => _b == Brightness.dark ? TokensDark.socialIconFgTumblr : TokensLight.socialIconFgTumblr;
  Color get socialIconFgInstagram => _b == Brightness.dark ? TokensDark.socialIconFgInstagram : TokensLight.socialIconFgInstagram;
  Color get navItemIconFg => _b == Brightness.dark ? TokensDark.navItemIconFg : TokensLight.navItemIconFg;
  Color get navItemIconFgActive => _b == Brightness.dark ? TokensDark.navItemIconFgActive : TokensLight.navItemIconFgActive;
  Color get navItemButtonIconFg => _b == Brightness.dark ? TokensDark.navItemButtonIconFg : TokensLight.navItemButtonIconFg;
  Color get navItemButtonIconFgActive => _b == Brightness.dark ? TokensDark.navItemButtonIconFgActive : TokensLight.navItemButtonIconFgActive;
  Color get sliderHandleBorder => _b == Brightness.dark ? TokensDark.sliderHandleBorder : TokensLight.sliderHandleBorder;
  Color get sliderHandleBg => _b == Brightness.dark ? TokensDark.sliderHandleBg : TokensLight.sliderHandleBg;
  Color get headerAbstract50Bg => _b == Brightness.dark ? TokensDark.headerAbstract50Bg : TokensLight.headerAbstract50Bg;
  Color get headerAbstract100Bg => _b == Brightness.dark ? TokensDark.headerAbstract100Bg : TokensLight.headerAbstract100Bg;
  Color get headerAbstract200Bg => _b == Brightness.dark ? TokensDark.headerAbstract200Bg : TokensLight.headerAbstract200Bg;
  Color get headerAbstract300Bg => _b == Brightness.dark ? TokensDark.headerAbstract300Bg : TokensLight.headerAbstract300Bg;
  Color get screenMockupBorder => _b == Brightness.dark ? TokensDark.screenMockupBorder : TokensLight.screenMockupBorder;
  Color get footerButtonFg => _b == Brightness.dark ? TokensDark.footerButtonFg : TokensLight.footerButtonFg;
  Color get footerButtonFgHover => _b == Brightness.dark ? TokensDark.footerButtonFgHover : TokensLight.footerButtonFgHover;
  Color get footerBadgeFg => _b == Brightness.dark ? TokensDark.footerBadgeFg : TokensLight.footerBadgeFg;
  Color get footerBadgeBorder => _b == Brightness.dark ? TokensDark.footerBadgeBorder : TokensLight.footerBadgeBorder;
  Color get footerBadgeBg => _b == Brightness.dark ? TokensDark.footerBadgeBg : TokensLight.footerBadgeBg;
  Color get appStoreBadgeBorder => _b == Brightness.dark ? TokensDark.appStoreBadgeBorder : TokensLight.appStoreBadgeBorder;
  Color get thumbnailBadgeBrandFg => _b == Brightness.dark ? TokensDark.thumbnailBadgeBrandFg : TokensLight.thumbnailBadgeBrandFg;
  Color get thumbnailBadgeSuccessFg => _b == Brightness.dark ? TokensDark.thumbnailBadgeSuccessFg : TokensLight.thumbnailBadgeSuccessFg;
  Color get toggleButtonFgDisabled => _b == Brightness.dark ? TokensDark.toggleButtonFgDisabled : TokensLight.toggleButtonFgDisabled;
  Color get toggleBorder => _b == Brightness.dark ? TokensDark.toggleBorder : TokensLight.toggleBorder;
  Color get toggleSlimBorderPressed => _b == Brightness.dark ? TokensDark.toggleSlimBorderPressed : TokensLight.toggleSlimBorderPressed;
  Color get toggleSlimBorderPressedHover => _b == Brightness.dark ? TokensDark.toggleSlimBorderPressedHover : TokensLight.toggleSlimBorderPressedHover;
  Color get alphaWhite90 => _b == Brightness.dark ? TokensDark.alphaWhite90 : TokensLight.alphaWhite90;
  Color get alphaWhite80 => _b == Brightness.dark ? TokensDark.alphaWhite80 : TokensLight.alphaWhite80;
  Color get alphaWhite70 => _b == Brightness.dark ? TokensDark.alphaWhite70 : TokensLight.alphaWhite70;
  Color get alphaWhite60 => _b == Brightness.dark ? TokensDark.alphaWhite60 : TokensLight.alphaWhite60;
  Color get alphaWhite50 => _b == Brightness.dark ? TokensDark.alphaWhite50 : TokensLight.alphaWhite50;
  Color get alphaWhite40 => _b == Brightness.dark ? TokensDark.alphaWhite40 : TokensLight.alphaWhite40;
  Color get alphaWhite30 => _b == Brightness.dark ? TokensDark.alphaWhite30 : TokensLight.alphaWhite30;
  Color get alphaWhite20 => _b == Brightness.dark ? TokensDark.alphaWhite20 : TokensLight.alphaWhite20;
  Color get alphaWhite10 => _b == Brightness.dark ? TokensDark.alphaWhite10 : TokensLight.alphaWhite10;
  Color get alphaBlack10 => _b == Brightness.dark ? TokensDark.alphaBlack10 : TokensLight.alphaBlack10;
  Color get alphaBlack20 => _b == Brightness.dark ? TokensDark.alphaBlack20 : TokensLight.alphaBlack20;
  Color get alphaBlack30 => _b == Brightness.dark ? TokensDark.alphaBlack30 : TokensLight.alphaBlack30;
  Color get alphaBlack40 => _b == Brightness.dark ? TokensDark.alphaBlack40 : TokensLight.alphaBlack40;
  Color get alphaBlack50 => _b == Brightness.dark ? TokensDark.alphaBlack50 : TokensLight.alphaBlack50;
  Color get alphaBlack60 => _b == Brightness.dark ? TokensDark.alphaBlack60 : TokensLight.alphaBlack60;
  Color get alphaBlack70 => _b == Brightness.dark ? TokensDark.alphaBlack70 : TokensLight.alphaBlack70;
  Color get alphaBlack80 => _b == Brightness.dark ? TokensDark.alphaBlack80 : TokensLight.alphaBlack80;
  Color get alphaBlack90 => _b == Brightness.dark ? TokensDark.alphaBlack90 : TokensLight.alphaBlack90;
  Color get alphaBlack100 => _b == Brightness.dark ? TokensDark.alphaBlack100 : TokensLight.alphaBlack100;
  Color get alphaWhite100 => _b == Brightness.dark ? TokensDark.alphaWhite100 : TokensLight.alphaWhite100;
  Color get alphaWhite5 => _b == Brightness.dark ? TokensDark.alphaWhite5 : TokensLight.alphaWhite5;
  Color get alphaWhite2 => _b == Brightness.dark ? TokensDark.alphaWhite2 : TokensLight.alphaWhite2;
  Color get alphaBlack5 => _b == Brightness.dark ? TokensDark.alphaBlack5 : TokensLight.alphaBlack5;
  Color get alphaBlack2 => _b == Brightness.dark ? TokensDark.alphaBlack2 : TokensLight.alphaBlack2;

  double get containerMaxWidthDesktop => 1280.w;
  double get containerPaddingDesktop => 32.w;
  double get containerPaddingMobile => 16.w;
  double get widthXxs => 320.w;
  double get widthSm => 480.w;
  double get widthLg => 640.w;
  double get widthXl => 768.w;
  double get width2xl => 1024.w;
  double get width3xl => 1280.w;
  double get width4xl => 1440.w;
  double get width5xl => 1600.w;
  double get width6xl => 1920.w;
  double get widthMd => 560.w;
  double get paragraphMaxWidth => 720.w;
  double get widthXs => 384.w;
  double get spacingNone => 0.w;
  double get spacingXxs => 2.w;
  double get spacingXs => 4.w;
  double get spacingMd => 8.w;
  double get spacingLg => 12.w;
  double get spacingXl => 16.w;
  double get spacing2xl => 20.w;
  double get spacing3xl => 24.w;
  double get spacing4xl => 32.w;
  double get spacing6xl => 48.w;
  double get spacing7xl => 64.w;
  double get spacing8xl => 80.w;
  double get spacing9xl => 96.w;
  double get spacing10xl => 128.w;
  double get spacing11xl => 160.w;
  double get spacingSm => 6.w;
  double get spacing5xl => 40.w;
  double get radiusNone => 0.r;
  double get radiusXxs => 2.r;
  double get radiusXs => 4.r;
  double get radiusSm => 6.r;
  double get radiusMd => 8.r;
  double get radiusXl => 12.r;
  double get radius2xl => 16.r;
  double get radius4xl => 24.r;
  double get radiusFull => 9999.r;
  double get radiusLg => 10.r;
  double get radius3xl => 20.r;
  double get textXs => 12.sp;
  double get textSm => 14.sp;
  double get textMd => 16.sp;
  double get textLg => 18.sp;
  double get textXl => 20.sp;
  double get displayXs => 24.sp;
  double get displaySm => 30.sp;
  double get displayMd => 36.sp;
  double get displayLg => 48.sp;
  double get displayXl => 60.sp;
  double get display2xl => 72.sp;
  double get text2xs => 10.sp;
  double get text3xs => 8.sp;
}

