// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3f2FsRBxYp4dl92BPKoOBegvaqnWVBfs',
    appId: '1:1065683669109:web:5b56910ea9f9953f7a283c',
    messagingSenderId: '1065683669109',
    projectId: 'adroit-outlet-444914-m0',
    authDomain: 'adroit-outlet-444914-m0.firebaseapp.com',
    storageBucket: 'adroit-outlet-444914-m0.firebasestorage.app',
    measurementId: 'G-Y4FD1G7Q1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkyzwpOShd1Fb-tuX6OB3wshg6KBs3bQ8',
    appId: '1:1065683669109:android:ba55a01b8fda9a087a283c',
    messagingSenderId: '1065683669109',
    projectId: 'adroit-outlet-444914-m0',
    storageBucket: 'adroit-outlet-444914-m0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFsqrnAL45_RPKB10cR_7-krdO4ZNNImk',
    appId: '1:1065683669109:ios:bc8f6a454fda378a7a283c',
    messagingSenderId: '1065683669109',
    projectId: 'adroit-outlet-444914-m0',
    storageBucket: 'adroit-outlet-444914-m0.firebasestorage.app',
    iosBundleId: 'com.porter.joyminis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFsqrnAL45_RPKB10cR_7-krdO4ZNNImk',
    appId: '1:1065683669109:ios:1213c52dcf3fde567a283c',
    messagingSenderId: '1065683669109',
    projectId: 'adroit-outlet-444914-m0',
    storageBucket: 'adroit-outlet-444914-m0.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3f2FsRBxYp4dl92BPKoOBegvaqnWVBfs',
    appId: '1:1065683669109:web:1b1b643bfd2739de7a283c',
    messagingSenderId: '1065683669109',
    projectId: 'adroit-outlet-444914-m0',
    authDomain: 'adroit-outlet-444914-m0.firebaseapp.com',
    storageBucket: 'adroit-outlet-444914-m0.firebasestorage.app',
    measurementId: 'G-TSRFTXZZSB',
  );
}
