///  AUTO-GENERATED BY packages/config/gen-codes.js
/// ❌ DO NOT EDIT MANUALLY

class AppErrors {
  AppErrors._();

  // =========================================================
  // 系统与通用
  // =========================================================

  /// [10001] System Error
  static const int systemError = 10001;

  /// [10002] Parameter Error
  static const int parameterError = 10002;

  // =========================================================
  // 身份与安全
  // =========================================================

  /// [40310] Device banned due to security risks
  static const int deviceBlacklisted = 40310;

  /// [40320] New device detected, verification required
  static const int deviceNotTrusted = 40320;

  /// [40323] Withdrawals disabled for 24h on new devices
  static const int deviceWithdrawLockedTemp = 40323;

  // =========================================================
  // 业务逻辑
  // =========================================================

  /// [40053] Order Number Error
  static const int orderNumberOrThirdPartyOrderNumberError = 40053;

  // =========================================================
  // 业务逻辑
  // =========================================================

  /// [40051] Order Number Error
  static const int orderNumberError = 40051;

  /// [40082] Group Already Exists
  static const int groupAlreadyExists = 40082;

  // =========================================================
  // 系统/通用
  // =========================================================

  /// [10000] Success
  static const int success = 10000;

  /// [40400] Not Found
  static const int notFound = 40400;

  /// [42900] Too Many Requests
  static const int tooManyRequests = 42900;

  // =========================================================
  // 身份/安全
  // =========================================================

  /// [20062] Invalid JWT Token
  static const int invalidJwtToken = 20062;

  /// [40100] Unauthorized
  static const int unauthorized = 40100;

  /// [40300] Forbidden
  static const int forbidden = 40300;

  /// [92000] User Not Found
  static const int userNotFound = 92000;

  // =========================================================
  // 钱包/支付
  // =========================================================

  /// [40009] Insufficient Balance
  static const int insufficientBalance = 40009;

  // =========================================================
  // 验证码/OTP
  // =========================================================

  /// [11002] OTP Expired
  static const int otpExpired = 11002;

  /// [11004] Too Many OTP Attempts
  static const int tooManyOtpAttempts = 11004;

  /// [11008] OTP Invalid or Used
  static const int otpNotVerifiedOrAlreadyUsed = 11008;

}
